### ISSUE TITLE
Add News header link

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#1079]
I always missed a simple and visible News link at decred.org. When I check any project, first thing I want is to know if it's dead or not, and I seek for News or Blog or something. This is a good practice seen in many FOSS projects:

- [Monero](https://www.getmonero.org/) (Blog)
- [Qubes OS](https://www.qubes-os.org/) (News)
- [Arch Linux](https://archlinux.org/) (News on home (!) + clickable `/news` link)
- [Zcash](https://z.cash/) (News & events)

Imo News shoud be here:

![site-header-no-news-sad-face](https://user-images.githubusercontent.com/24484727/189496700-fa78c542-12d8-434f-91ba-1857006349eb.png)

Sadly it was discussed for years in #561 but we still don't have it. In the spirit of the [D.R.E.A.M. 2 proposal](https://proposals.decred.org/record/5ef57f7) I suggest to get *something* done and improve it as we go.

Proposed implementation:

- Rename `/press` content to `/news`, add redirect.
- Change the `Coverage / Releases` toggle to `News / Press`.
- Hide press-related text ("Decred has been prominently...") in the News mode, show in Press mode.
  - tbh I'd consider removing showing press releases in the same feed with News to better expose them without asking the user to do extra clicks. New press release is "News" after all.
- Add News as a big top-level nav link to site header.
  - If it makes header too wide, shorten Documentation to Docs.

**Comment by jholdstock** [comment]
I agree with pretty much all of this. Not hard to implement and a decent improvement to the site.

Any thoughts @jzbz?

**Comment by jzbz** [comment]
I'm fine with it being added to the header, and renaming Documentation to Docs as suggested so it doesn't look too cluttered.
