### ISSUE TITLE
Kucoin now accepting DCR deposits again. Should be added to Exchanges

### ISSUE THREAD

**Issue by exitus1** [decred/dcrweb#1087]
See their announcement: https://www.kucoin.com/pl/news/pl-pl-en-kucoin-opens-mainnet-dcr-tokens-deposit-and-withdrawal-services-20220924

**Comment by xaur** [comment]
A shorter English link: https://www.kucoin.com/news/en-kucoin-opens-mainnet-dcr-tokens-deposit-and-withdrawal-services-20220924

**Comment by xaur** [comment]
Linking - KuCoin was recently removed in #1064
