### ISSUE TITLE
Add DCRDEX to Wallets page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#1122]
DEX client increasingly belongs to the [Wallets](https://decred.org/wallets/) page. @buck54321 is it time to add it or shall we wait?

> As we expand wallet functionality, we're going to make an effort to target the largest possible market. Our plan is essentially a pivot from a "DEX trading app" to a "state-of-the-art multi-wallet backed by Decred's DEX network". \[https://proposals.decred.org/record/ca6b749\]

**Comment by buck54321** [comment]
Okay with me.

**Comment by xaur** [comment]
It's live.
