### ISSUE TITLE
Update Community page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#1126]
Our [Community](https://decred.org/community/) page might need an update after the May 1 [announcement](https://matrix.to/#/!lDZCzVQjFoJsXMPkvr:decred.org/$jO-Hc1bk0SGjON0JrJvLwzLNeF6pzg-bAgwXT5lv-BA) about changes to Decred's chat platforms.

I don't know if all items are implemented already but looks like we should remove the following links:

- Discord
- Support Channel on Discord
- Support Channel on Telegram

cc @jzbz

**Comment by jzbz** [comment]
Ignore last, Discord is still being used just independently from the other platforms now (not bridged).
So only the support links need to be removed as all support takes place on Matrix.
