### ISSUE TITLE
Add Cryptopower to /wallets

### ISSUE THREAD

**Issue by dreacot** [decred/dcrweb#1143]
https://github.com/crypto-power/cryptopower

**Comment by xaur** [comment]
@jholdstock can you please advise how `highlight: true` works in [wallets.yml](https://github.com/decred/dcrweb/blob/master/src/data/wallets/wallets.yml)?

Also, I wonder if we can use the `core_software` tag? Technically Cryptopower is not "core software" (yet, heh), but neither is DCRDEX. It looks like the real meaning of the tag is more like "open-source software built by the Decred community".
