### ISSUE TITLE
Add Exchange: mexc

### ISSUE THREAD

**Issue by exitus1** [decred/dcrweb#1157]
https://www.mexc.com/exchange/DCR_USDT

Notable that VPN allows anyone to use this exchange

**Comment by xaur** [comment]
Nice! Do we have any test reports from community members?

**Comment by exitus1** [comment]
![image](https://github.com/decred/dcrweb/assets/46197055/954c441c-7a9e-4e8d-9a8e-e8588a66895f)
Deposit

![image](https://github.com/decred/dcrweb/assets/46197055/9b8e0799-2089-4183-9f0e-3f2903e925a7)
Withdrawal

![image](https://github.com/decred/dcrweb/assets/46197055/0e5ebd8a-5bbd-48fa-9446-435c05d067eb)

In wallet
