### ISSUE TITLE
Apple desktop OS format inconsistency

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#117]
Apple's desktop OS is mentioned in different formats. It is written as: Mac OS X, Mac OS, or macOS.

It would be best to have one format, for example: MacOS.

**Comment by jolan** [comment]
This has been recently fixed but the update was not pulled and made live.  I will make sure this happens.

Duplicate of #114.

**Comment by jolan** [comment]
Update is live if you want to review.
