### ISSUE TITLE
add decrediton windows release

### ISSUE THREAD

**Issue by jolan** [decred/dcrweb#126]
Not sure if binary will show up today or not. Need to at least:

- [x] add link on downloads page

Depending on the quality/feedback:

- [x] change Windows download link at the top of the main page from paymetheus to decrediton?
- [ ] change Windows download link in the tour portion of the main page from paymetheus to decrediton?

**Comment by jolan** [comment]
Rest of the issue was completed in #144 / #145.

**Comment by jolan** [comment]
The tour text ("The Wallets") still needs to be updated.

**Comment by nickboariu** [comment]
It looks like the paymetheus link has been removed from the tour text. Now, there's a link to the downloads page anchored to the Decrediton wallet.
I think this issue could be closed.

**Comment by jolan** [comment]
I was waiting for the site to be updated but that is imminent so I'll just close this now.
