### ISSUE TITLE
Branding page requires trailing slash.

### ISSUE THREAD

**Issue by davecgh** [decred/dcrweb#154]
Attempting to access the branding page on decred.org without a trailing slash results in a 404 not found error.

To be more specific:

|URL|Result|
|-|-|
|https://decred.org/brand|404 Error|
|https://decred.org/brand/|Works|
|https://www.decred.org/brand|404 Error|
|https://www.decred.org/brand/|Works|

It should work with or without the trailing slash.

**Comment by sndurkin** [comment]
Same with https://decred.org/downloads
