### ISSUE TITLE
Stakepool user count

### ISSUE THREAD

**Issue by infertux** [decred/dcrweb#156]
![2017-10-25-060421_310x223_scrot](https://user-images.githubusercontent.com/345702/31982931-6b6071e4-b94a-11e7-993f-f5f339f98096.png)

The list of stake pools on decred.org currently shows the total user count for each pool. This figure is misleading IMO since typically half of these "users" don't actually stake. I think it'd make more sense to show the *active* user count as a metric.

The active user count is computed as [any user who has submitted an address](https://github.com/decred/dcrstakepool/blob/master/models/user.go#L98-L100). Ideally, I think it should be any user who has bought at least 1 ticket on the pool because one can submit an address then never actually stake.

Thoughts?

**Comment by jolan** [comment]
The stake pool API exports UserCount and UserCountActive but https://github.com/decred/dcrwebapi is being converted from PHP to Go.  Just need to add the field to dcrwebapi once that is done and make the corresponding change on the stake pool list.
