### ISSUE TITLE
no js: degrade animations to static images

### ISSUE THREAD

**Issue by behindtext** [decred/dcrweb#168]
when viewing the new site with no javascript, the animations spin the cpu unnecessarily.

i suggest replacing the animation on the right panel of the landing screen with a fixed image. this should fix most of the cpu churn.

the js image that shows the total # of coins mined shows "We're sorry, but this Website doesn't work properly without JavaScript enabled." when js is disabled. i suggest using a static image here as well.

when js is disabled, the animated gif showing the 2 users hi-fiving should be a static image.

**Comment by linnutee** [comment]
Total coins one is the trickiest, this needs a better solution later on. I recon currently best fallback is just demoting it to illustration. Adding any copy will add more clutter and we can't really show the coins mined or any data visualization w/o js. I'll create the graphic for this next.

**no.js headers for subpages**:
http://decred-v5-nojs-edition.webflow.io/decred-contractors
http://decred-v5-nojs-edition.webflow.io/decred-stakepools
http://decred-v5-nojs-edition.webflow.io/decred-press
http://decred-v5-nojs-edition.webflow.io/decred-downloads

Pngs:
![press-nojs](https://user-images.githubusercontent.com/17774057/32636216-78ace6ba-c5bc-11e7-8676-179325802c97.png)
![downloads-nojs](https://user-images.githubusercontent.com/17774057/32636217-78c712ce-c5bc-11e7-96cc-b4bb9df91eb0.png)
![stakepools-nojs](https://user-images.githubusercontent.com/17774057/32636219-78e4f6b8-c5bc-11e7-8f50-0ea499b94559.png)
![contributors-nojs](https://user-images.githubusercontent.com/17774057/32636220-7909c5a6-c5bc-11e7-922a-c97e4135045e.png)
