### ISSUE TITLE
fix gap below total mined image on mobile

### ISSUE THREAD

**Issue by behindtext** [decred/dcrweb#171]
on iOS, there is a big whitespace gap below the image that shows the total mined.

besides this, the mobile site renders nicely.

**Comment by linnutee** [comment]
The same issue was already fixed in Sanders production site: http://decred-v5.webflow.io
Just needs implementation.

**Comment by dajohi** [comment]
Is this still an issue or can this be closed?

**Comment by jolan** [comment]
Still an issue.
