### ISSUE TITLE
Add JS Piwik Tracking code to video on homepage

### ISSUE THREAD

**Issue by timhebel** [decred/dcrweb#174]
I need someone to add a line of JavaScript code from Piwik here: https://piwik.org/docs/event-tracking/  What we need is in the 'Javascript trackEvent()' section of that page, and it has some specific instructions on making an event for a video play. Basically we need Piwik to log the event that the video has been launched/played for use in Piwik Goals.

Please DM me in Slack @timhebel if you have any questions.

**Comment by peterzen** [comment]
It's implemented in https://github.com/decred/dcrweb/pull/166

**Comment by jolan** [comment]
Events are being populated in piwik, closing.

**Comment by timhebel** [comment]
Thanks gentlemen!
