### ISSUE TITLE
Decred.org first loading page 'glitch'

### ISSUE THREAD

**Issue by Arriu** [decred/dcrweb#176]
Now that the white flashing frame has been fixed, the first impression is almost flawless. However, 'almost' because when first loading decred.org, there is still a 'glitchy' effect of the background jumping when going from the very first frame, where the site has not identified your OS yet, and the next, where it has. This is represented in the first/top and second/bottom frame of the attached png.

![jump](https://user-images.githubusercontent.com/27448641/32552787-591c58bc-c495-11e7-9bdc-2fd55650dac8.png)

**Comment by linnutee** [comment]
Happens due to js loading – afaik this can only be fixed by creating a page Loader in the future. 
Noted it down though.

**Comment by oktapodia** [comment]
I'm not sure the [resizing](https://github.com/decred/dcrweb/blob/4a80b82af18ab243e097b700935d251bff2ec01f/www-root/content/js/main.js#L598) is mandatory, @linnutee what do you think?

**Comment by saender** [comment]
Good notice @oktapodia .

Should delete the js part (from line 596 to 606) of the code and apply new css rules to .bg-gradient and .bg-illustration, e.g:

`.bg-gradient {
	width:  calc(50% + 80px) !important;
}
.bg-illustration {
	width:  calc(50% - 80px) !important;
}`

Regards.
