### ISSUE TITLE
Move "Contributors" to end of first page

### ISSUE THREAD

**Issue by rramires** [decred/dcrweb#179]
Hi, the site is beautiful. https://decred.org/ 
But to find the team, you have to click on the menu, then on "Contributors".
https://decred.org/contributors/
Maybe it's best to put it at the end of the first page, just by moving the scroll down there.
So in a complete scrolling the "lazy visitor" coming in for the first time can see that there are many people working in the project, without having to search it.

**Comment by linnutee** [comment]
Thanks for feedback. However it's very unlikely that we can add this much to the front-page, the clean and nice first impression will get lost easily. Suggested approach may work in case of only 3 or 4 "frontmen", but unlike some other projects, we don't have them and it goes against a community consensus.

The current contributors page already includes a larger amount of people and a requested future iteration might make it more complex by including a fuller list of active contractors (number of factors come to play here). Aiming to keep balance in the marketing optics of presenting the force and legitimacy of the people working on Decred as well giving everyone involved a fair representation.

**Comment by nickboariu** [comment]
@linnutee What do you think about changing the footer where it says "Decred Developers" in the first column, to link to the contributors page?

**Comment by jzbz** [comment]
This can be closed.
