### ISSUE TITLE
Downloads page should have instructions for verification

### ISSUE THREAD

**Issue by sndurkin** [decred/dcrweb#181]
There have been a few people in Slack asking how to verify the checksums for binary downloads, and someone has to give them [this link](https://github.com/decred/decred-binaries/blob/v1.1.0/README.md#verifying-binaries); it should probably be linked to from the downloads page.

**Comment by nickboariu** [comment]
Is something like this ok?
![decred-dcrweb-downloads-binary-checksums](https://user-images.githubusercontent.com/12702524/33251222-6a5536cc-d2ea-11e7-8074-e021a866d99d.PNG)

**Comment by oktapodia** [comment]
Looks good for me, @sndurkin what do you think?

**Comment by sndurkin** [comment]
Yep, looks good to me too.

**Comment by nickboariu** [comment]
Should I create a branch for this commit?

**Comment by nickboariu** [comment]
Sorry about the mess. I forgot to create a branch so reverted commits to master and recommitted from branch
