### ISSUE TITLE
No sitemap.xml file, unless I'm not finding it.

### ISSUE THREAD

**Issue by timhebel** [decred/dcrweb#183]
For SEO purposes, we need a sitemap.xml file. (unless it is called something irregular and I'm missing its existence, but it should be at the link decred.org/sitemap.xml)

It needs to be listed in the robots.txt file: https://decred.org/robots.txt and it needs to be submitted to Google Webmaster Tools.

Thanks,
Tim

**Comment by nickboariu** [comment]
Created and submitted to @karamble

**Comment by timhebel** [comment]
I'm not seeing it @nickboariu @karamble https://decred.org/sitemap.xml/

**Comment by alexlyp** [comment]
we haven't updated the prod site yet, remain calm.
