### ISSUE TITLE
Hodlmoon Sweater for Decred

### ISSUE THREAD

**Issue by karamble** [decred/dcrweb#199]
In order to get the chance to produce Decred 'Ugly Sweaters' at hodlmoon dot com Ingsoc requested to host a pdf and an ai design mockup file on the decred website. Designs were provided by Lustosa and should be hosted in the media directory.

**Comment by realingsoc** [comment]
Confirming that this information is correct. We're trying to bring sexy back.

Reference: https://hodlmoon.com
