### ISSUE TITLE
English still being shown on translation.

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#210]
The following  text still appears in English on https://decred.org/ja/ or any other language.

> For those who like to tinker, Decred provides a full suite of command line tools allowing customization of the Decred experience.

**Comment by gravityz3r0** [comment]
Just to add, the same English text shows up in ALL languages, at the same location

**Comment by jholdstock** [comment]
![s](https://user-images.githubusercontent.com/6762864/33966136-64ff3a64-e056-11e7-9206-e5b92f38b3bf.jpg)

**Comment by jamiekeefer** [comment]
The string is in the POT file so likely needs new PO files generated after string translation, did not see string in ja language PO file - did not check others.

![image](https://user-images.githubusercontent.com/2806776/35483690-1bfbe908-0413-11e8-8c32-5b401bb1ea86.png)

**Comment by peterzen** [comment]
I've requested a translation update on all languages; will merge them in once we get them.

**Comment by ZeroASIC** [comment]
At least some of these translations are in the POT, but the HTML has been updated since then so when the files get generated the string replacement no longer picks up on it.

**Comment by peterzen** [comment]
I re-generated the POT and pushed it to Transifex, most translation do indeed need to be updated: 
![image](https://user-images.githubusercontent.com/5878500/50044065-a07df780-007e-11e9-8173-23d81297aee4.png)

**Comment by jholdstock** [comment]
This can be closed.
