### ISSUE TITLE
Portuguese translation errors

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#211]
Corrections have been made by Bernardo (@Bebrites on Slack), some of them were integrated into the translation and some were not. It's also important to note that there are significant differences between Brazilian Portuguese and European Portuguese, this was clearly not taken into consideration by the translation service. We are primarily targeting Brazil.

Fixes:
https://docs.google.com/spreadsheets/d/1o_CCEzm0V7w68zTTFwy34spJ-xN7N4swyEj-Tkf04l8/edit?usp=sharing

Edit: @emiliomann in Slack should have his group do the final review on any changes, many of them have crypto domain knowledge that was clearly lacking from the pro service we used.

**Comment by rgeraldes** [comment]
@jzbz European Portuguese here, in case you need help.

**Comment by isaias** [comment]
@jzbz Should that issue keep open after merged?
