### ISSUE TITLE
Compare chart should be on the homepage tab menu

### ISSUE THREAD

**Issue by bebrites** [decred/dcrweb#212]
Shouldn't we be able to access the compare chart through Decred's homepage? 
It's so well done, it's a shame you can only access it through Social media or if you had the link.
https://decred.org/compare
It could be on the menu, below get started.
Thanks

**Comment by linnutee** [comment]
No, its intended to be separate.

**Comment by bebrites** [comment]
Why is that?

**Comment by karamble** [comment]
Issue can be closed.

The decision to put the compare page into a seperate subpage was a decision by the design team who created it. We do not want to put it into the main navigation as we do not want to have it placed so popular as it can be perceived wrong and lead to negative discussions. The direct link to the compare page can be used to point users to it or publish it on social media. Once a news section is added to the website we can think about placing it there.

**Comment by Tsunekazu** [comment]
Due to bad publicity it is receiving on Twitter and because of the extremely subjective nature of the comparison, and the untenability of the result score (ie. DASH scoring better than Bitcoin?!) I propose to remove it from the official website altogether.
