### ISSUE TITLE
News page

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#214]
I've opened this issue because we have a link "News (Coming soon)" but there doesn't seem to be any issue to implement that page. 

Copying over some resources from decred/dcrdocs#138:

> Just want to keep a log until we decide:
> https://www.cryptocoinsnews.com/decred-benefits-bitcoin-impasse-joins-altcoins-rise/
> https://www.investitin.com/decred-altcoin-review/
> https://decentralize.today/ethereum-is-not-a-cryptocurrency-d76b1d86109
> https://www.youtube.com/watch?v=jSyrUTLZQV8
> http://finance.yahoo.com/news/decred-releases-v1-0-worlds-223000706.html
> http://www.coindesk.com/800-growth-q1s-top-performing-cryptocurrencies-posted-big-gains/
> https://www.youtube.com/watch?v=428acb4jwBM

> I'm keeping an updated sheet with press coverage. When the media page gets built, you can use this as a resource https://docs.google.com/spreadsheets/d/10Vz4-t4G9xv9Lkle67OhcwWWTkK_NNNloDD81raeLKw/edit#gid=0

**Comment by jzbz** [comment]
https://decred.org/press/ has been created.
Navigation menu just needs to have the link added.

**Comment by jholdstock** [comment]
Link "Decred in the Press" has been added to the homepage footer.
