### ISSUE TITLE
Enable indexes on /media/

### ISSUE THREAD

**Issue by dajohi** [decred/dcrweb#246]

**Comment by ZeroASIC** [comment]
The media directory shouldn't be directly accessible in the current implementation.  The media it contains should be linked to from parts of the website and will get indexed by search engines in that context.  Unless you want to add a media page that contains links and previews to all of the content it contains.  It's not currently in the sitemap and work plan found in #257

**Comment by dajohi** [comment]
http://nginx.org/en/docs/http/ngx_http_autoindex_module.html#autoindex

**Comment by ZeroASIC** [comment]
I just enabled it site wide in #526, but I could change it to just this folder.

**Comment by peterzen** [comment]
> I just enabled it site wide in #526, but I could change it to just this folder.

It's not a good idea - files should be referenced directly from the content - if a file is not accessible from anywhere it's not used and should be removed.  

What's the use case for enabling the index on `/media`?
