### ISSUE TITLE
Add this articles to /Press

### ISSUE THREAD

**Issue by bebrites** [decred/dcrweb#249]
Add the following Articles to Decred.org/Press

https://coincentral.com/decred-lowdown-decentralized-blockchain-governance/ - Coin Central

https://www.investinblockchain.com/cryptocurrency-projects-march-2018/ - Invest In Blockchain

https://themerkle.com/what-is-decred/ - The Merkle

https://btcmanager.com/beginners-guide-decred/ - BTC Manager

https://www.blockchaintechnology-news.com/2018/01/23/atomic-swaps-decentralised-exchange-community-decred/ - The Block - Blockchain Technology News

Thanks!

**Comment by jzbz** [comment]
Those pieces are all decent.

**Comment by xaur** [comment]
This is one of my favorites as it emphasizes sovereignty, please consider it too:

https://www.blockchaintechnology-news.com/2018/01/23/atomic-swaps-decentralised-exchange-community-decred/

**Comment by bebrites** [comment]
Great find Xaur! I agree

**Comment by bebrites** [comment]
Added to the original post @xaur  :)
