### ISSUE TITLE
Local Dev Environment Not Working - Missing Instructions?

### ISSUE THREAD

**Issue by StabbarN** [decred/dcrweb#254]
See instructions https://github.com/decred/dcrweb#development

It was working a few weeks ago. My setup:
Latest Mac OS
Npm version 5.6.0
Node version 8.9.4
grunt-cli 1.2.0
grunt 0.4.5

```
grunt watch
Running "watch" task
Waiting...
(node:3358) ExperimentalWarning: The http2 module is an experimental API.
```

```
grunt serve
(node:3359) ExperimentalWarning: The http2 module is an experimental API.
Running "replace:dist" (replace) task
>> 0 replacements in 8 files.

Running "gt_generate_html:l10n" (gt_generate_html) task

Running "copy:main" (copy) task
Created 13 directories, copied 402 files

Running "connect:server" (connect) task
Waiting forever...
Started connect web server on http://localhost:8080
```

I did the instructions but can't get the page to load. See screenshot:
<img width="1205" alt="dcrweb local dev" src="https://user-images.githubusercontent.com/921390/36946773-676ce890-1fc2-11e8-9833-ba4d979b9f47.png">

**Comment by knightjdr** [comment]
This [PR](https://github.com/decred/dcrweb/issues/129) was supposed to fix it. I haven't been able to get it working myself.
