### ISSUE TITLE
New exchanges listing Decred

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#299]
https://support.okex.com/hc/en-us/articles/360004847791-Decred-DCR-Now-Available
https://www.huobi.pro/notice_detail/?id=1855

**Comment by linnutee** [comment]
Any thoughts what to tag these with?

**Comment by jzbz** [comment]
@linnutee Yes, "high liquidity" for Huobi, nothing for OKEx.
We've also got a couple to add to the OTC section:
https://cumberlandmining.com/
https://onechaincapital.com/

**Comment by jzbz** [comment]
Got an additional OTC desk to add which trades Decred.
https://www.kryptonite.li/
