### ISSUE TITLE
Sharp and clean font rendering for dcrweb.

### ISSUE THREAD

**Issue by saender** [decred/dcrweb#300]
By adding code below to the **html** element (source: https://gist.github.com/hsleonis/55712b0eafc9b25f1944):

`html {
  /* Adjust font size */
    font-size: 100%;
    -webkit-text-size-adjust: 100%;
    /* Font varient */
    font-variant-ligatures: none;
    -webkit-font-variant-ligatures: none;
    /* Smoothing */
    text-rendering: optimizeLegibility;
    -moz-osx-font-smoothing: grayscale;
    font-smoothing: antialiased;
    -webkit-font-smoothing: antialiased;
    text-shadow: rgba(0, 0, 0, .01) 0 0 1px;
  }`

Did a before and after comparison screenshots:
![fontbeforeafter](https://user-images.githubusercontent.com/29069168/41480478-4edc4b2a-70d7-11e8-9320-ce734400235b.png)
#

**Comment by rmykolas** [comment]
This can be closed
