### ISSUE TITLE
Fixes to Roadmap and Press 

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#302]
@rmykolas 
1 Update roadmap icons for Initial Privacy Release and Identity Release 
(rendering issues and other should have dcr symbol)

2 Add 50% #091440 overlay to Roadmap header gif (or something close to that with good contrast and obfuscating gif quality)

3 Replace copy for Identity release (seems mixed up with SPV)
```
{
"title": "Identity Release",
"status": "Completed",
"added": "Q3 2016",
"completed": "Q1 2017",
"description": "Create an engaging and recognisable identity and a design system to clarify the rationales integrated into Decred. Work out a common vision and a set of principles to bring longevity, togetherness and representation for it, both as a cryptocurrency and as a project in any environment.",
"link": "https://medium.com/decred/decred-developing-identity-and-design-system-for-a-digital-currency-17df76ab67c8"
}
```

4 When the Roadmap page opens, can we have “New” tab selected by default instead of displaying all? 

5 Check if cache issue or can be recreated – potentially on FF, Roadmap header has may have some bug strokes on left and right edges.

6 (IF easy to fix), flush all those cards listings to the left. I see currently the new rows are added by height, after the shortest, but would be more logical to always have them start from left. Can leave this to the future also if it’s more a picking task. 

7 Few articles will need to be removed from Press/Coverage, will be listed in #web_ops

[dcrweb - roadmap - symbols - 220618.zip](https://github.com/decred/dcrweb/files/2128534/dcrweb.-.roadmap.-.symbols.-.220618.zip)

**Comment by rmykolas** [comment]
This can be closed
