### ISSUE TITLE
Remove advisors section from site.

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#316]
As a decentralized project it doesn't make sense for us to engage in appeal to authority. Listing famous people who own or like Decred creates a conundrum for the project as I've been approached by several individuals who wish to be considered for inclusion and there's no clear process for determining who should be added.

Not to discount the contributions of any individual, however there must be some litmus test which includes the person actively engaging in the project on a sustained basis to be eligible for inclusion on the site in my opinion.

I'm happy to hear any thoughts on this, and if there's a great deal of contention over this issue we can always use Politeia to settle it in the near future.

**Comment by thedecreddigest** [comment]
I'm also in favour of removing the advisors section. I think the current advisors would agree that it’s the right thing to do too, given that we are a decentralised project.

**Comment by alexlyp** [comment]
Agree with this 100%

**Comment by noahpierau** [comment]
This issue can be closed, the section is gone https://decred.org/contributors/
