### ISSUE TITLE
Watch Video button looks kinda crappy (mobile)

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#319]
Looks like the default link style has not been overridden correctly?

![screenshot_20180809-195000_chrome](https://user-images.githubusercontent.com/6762864/43919356-98d190b2-9c0d-11e8-8599-bb8177db4dc7.jpg)

**Comment by linnutee** [comment]
Good find, should be as following: https://xd.adobe.com/spec/3c7f2d39-c6af-4913-5e37-6e715d6da79d-4a4e/
