### ISSUE TITLE
Jargon update: change stakepool to Voting Service Provider

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#324]
As part of the efforts to make Decred more appealing to the general public, we are updating our jargon. One of the proposed changes is changing from stake pool or stakepool to Voting Service Provider (or VSP for short). The rationale is explained [here](https://www.reddit.com/r/decred/comments/95r578/proposed_changes_to_decred_jargon/e3uu14p).

The pages that need to be updated: 
https://decred.org/stakepools/ Text updates and new URL (old URL forwards to the new one)
https://decred.org/#guide Text updates, in particular the PoS section (change to PoS voting).

**Comment by rmykolas** [comment]
What should be the /stakepools new URL - /voting-service-providers, /votingserviceproviders or something different?

**Comment by s-ben** [comment]
Per the [approved Pi proposal](https://proposals.decred.org/proposals/522652954ea7998f3fca95b9c4ca8907820eb785877dcf7fba92307131818c75) on jargon change, we're now also changing Proof-of-Stake "mining" to "voting. Do we want to just bundle that change into this Issue? 

From the proposal: 

...we shall change the words we use to refer to:

- Proof of Stake "mining" to "voting"

- "Stakepools" to "Voting Service Providers" (VSPs)

**Comment by ZeroASIC** [comment]
Yeah, I think so.  If no one else is working on this I can do it.

**Comment by s-ben** [comment]
@ZeroASIC cool. I'm relatively new to the project as well, but generally, if nobody has claimed a task on an Issue, you can just go ahead and do it. I've also noticed that it's generally encouraged on other repos to announce what you intend to work on in the relevant slack channel, just to give other devs a heads up.

**Comment by ZeroASIC** [comment]
@s-ben There's no channel for dcrweb.  I'll take a look at it later, maybe tonight.

**Comment by ZeroASIC** [comment]
I updated decred.org/stakepools/ to decred.org/vsp/ because decred.org/votingserviceprovider/ seemed a bit too long to me.  I could change it though.
