### ISSUE TITLE
Link to matrix community rather than general room

### ISSUE THREAD

**Issue by jrick** [decred/dcrweb#325]
https://decred.org/community/

The matrix/riot icon links to https://riot.im/app/#/room/#general:decred.org (this is already unfortunate, as it should be linking through matrix.to), but there are many other decred matrix rooms that are not easily discoverable through this link.  Instead, a link to the +decred:decred.org community should be provided instead: https://matrix.to/#/+decred:decred.org

**Comment by dajohi** [comment]
Closed via #326
