### ISSUE TITLE
clicking an already-open title/link on the tour causing vertical expansion

### ISSUE THREAD

**Issue by jolan** [decred/dcrweb#33]
i.e. go to the site, overview is highlighted.  click overview a few times and see the vertical line height grow.

**Comment by karamble** [comment]
Confirmed, the javascript maths adding constantly to the height: value of the div
![error](https://cloud.githubusercontent.com/assets/25404928/22909268/5a6bb01a-f253-11e6-840c-3bb08f4b44f7.png)
