### ISSUE TITLE
Add Guarda to 3rd party wallets

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#339]
On the page https://decred.org/downloads/ add Guarda to 3rd party wallets.

Note from Guarda: _currently Guarda is represented by Web and Desktop multi-currency wallets, Android wallet will be launched in two weeks as well. 10 000 active users, 24 supported coins, built-in coin purchases, built-in exchanges, private keys import and export, non-custodial._

The link can go to https://guarda.co/ so users can choose Web, Android or Desktop.

As for the image, see attachment:
![guarda-shield-logo](https://user-images.githubusercontent.com/16287891/45698493-6f1d8a80-bb68-11e8-851e-78ac5a19ad44.png)

**Comment by jzbz** [comment]
Will need to verify this one works. When they originally announced Decred support someone was able to send DCR to the wallet but it never showed up.

**Comment by noahpierau** [comment]
DCR was added to https://guarda.co/supported-cryptocurrencies so I assume they are serious.

I verified that their web wallet deposit works:
![image](https://user-images.githubusercontent.com/16287891/45806501-82903900-bcc1-11e8-887c-551a2f18a8fc.png)

I was also able to withdraw funds, but this process wasn't without bugs: (or time travel is real)
![image](https://user-images.githubusercontent.com/16287891/45807132-0e569500-bcc3-11e8-8cdc-73126bcbe763.png)

**Comment by rmykolas** [comment]
So should this be added after all?
