### ISSUE TITLE
Extended /compare page cannot be accesses without javascript

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#358]
Now extended compare page has its own URL: https://decred.org/compare/#extended

But since this was implemented with javascript, there is still no way to read the extended view without js. Extra unpleasant consequence is the page cannot be archived.

Archiving is important because it captures what the web page asserted at a given point in time. Not the case for Decred, but normally I always look with suspicion at pages with un-archivable dynamic content. It allows to evade web notaries and retroactively change content.

**Comment by linnutee** [comment]
Can be closed if https://github.com/decred/dcrweb/issues/370 is closed.
