### ISSUE TITLE
Create Decred brief page

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#366]
Create a https://www.decred.org/brief page that will host the content in the linked document below. We would also like to have a PDF download option for easier printing/distribution through email etc...

https://docs.google.com/document/d/1W3k-qNRZvWMlFEtzvBZnUEJc8gtZ3rsurAKIJNGykaM/edit

**Comment by linnutee** [comment]
Ok before we can add the Brief subpage, going with this smaller update instead of the current pdf found at footer: 
https://decred.org/business_brief.pd

Replaced with: 
[decred - brief - 10.2018.pdf](https://github.com/decred/dcrweb/files/2479322/decred.-.brief.-.10.2018.pdf)
