### ISSUE TITLE
Compare page outdated

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#370]
Some of the criticism here has merit: https://twitter.com/hasufl/status/1044914023018483712

* Bitcoin fees are much lower now.
* Comparing block time with happy and unhappy faces is wrong. Security and cost to rewrite the chain is what matters, not the block time.
* @thedecreddigest can provide more insights

**Comment by Tsunekazu** [comment]
Agreed. Either remove the page altogether or remove the "ratings" / faces part.

**Comment by jzbz** [comment]
I think the page served its purpose and is no longer of value. Makes sense to remove it completely.

**Comment by noahpierau** [comment]
Another vote for removing here, plus adding a redirect to the homepage. I do think we should save the content so we can re-hash it at a later occasion (with updated numbers, of course).
