### ISSUE TITLE
Add CoinEx to exchanges list

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#388]
URL: https://www.coinex.com/
Logo: https://www.coinex.com/_nuxt/img/coin-ex-logo.c2d86a1.svg

**Comment by linnutee** [comment]
Isolated the symbol, this is fitting now: 
[coinex - symbol.svg.zip](https://github.com/decred/dcrweb/files/2492854/coinex.-.symbol.svg.zip)
