### ISSUE TITLE
Community page - explain comms bridging

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrweb#393]
It has just struck me that for people who don't know that main communications platforms are bridged, the /community page must be quite confusing. 
The bridging is itself a strong characteristic that offers community members a choice of chat platforms.
I think a note should be added to the top of this page which explains that channels on Matrix, Slack and Discord are all bridged together - so that people trying to find the Decred community know that it's more important to consider which platform you prefer than where the majority of other people are. 
Except Telegram and a few platforms, which are not bridged to anything else and probably shouldn't be recommended.

**Comment by xaur** [comment]
RocketChat is also bridged iirc.

**Comment by linnutee** [comment]
This can likely be solved in the default description area. So would need the copy to be written, then it can be updated.

<img width="1403" alt="screen shot 2018-10-17 at 18 41 46" src="https://user-images.githubusercontent.com/17774057/47098770-88375b00-d23c-11e8-9e7a-b9fa028502c4.png">

**Comment by RichardRed0x** [comment]
How about:
The public channels on Matrix, Slack, Discord and Rocket.Chat have been bridged. If you use any of these platforms you will see messages from the Decred community members on the others.
