### ISSUE TITLE
Copywriting request: Governance subpage

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#408]
This item has been long on the backburner. As Pi mainnet was launched, it's time to get subpage released giving a bit more deeper insight on the projects governance. Would take the MVP approach here and get a simple version up first, which can later be iterated upon. 

The page needs to cover the basics of Governance (as the kind of DCR's meme), what it is, why it's needed and roughly how it works. As well have a dedicated section for introducing Politeia. As short and straight-forward as possible. 

EETER will produce any related visual content as well design and implement page. In need of copywriters to produce the textual content. @Dustorf provides insight on marketing perspective and needs. 

Request for involvement #writers-room: Richard-Red, Jazzah

**Comment by RichardRed0x** [comment]
Happy to help with this. I wrote a [governance page for docs](https://docs.decred.org/governance/governance/) a while back (and a page for [Politeia](https://docs.decred.org/governance/politeia/)), maybe you could review that as a starting point and offer some pointers on how to tailor the content for dcrweb @linnutee?

**Comment by Dustorf** [comment]
Tanel-where will this page exist on the site and how will people get there?

**Comment by s-ben** [comment]
Hey all. Thinking about tweeting this issue out on the [good-first-issue Twitter account](https://twitter.com/dcrgoodfirst), but wanted to make sure it's still active first. If someone jumps in here to help, will they get a timely response?

**Comment by RichardRed0x** [comment]
Seems a bit stale, more than a year ago... I guess the page has probably been written now as the new site has made a lot of progress since then.

**Comment by s-ben** [comment]
I see. Looking at all the 'help-wanted' labeled issues, all look like they're maybe stale? Close them?

https://github.com/decred/dcrweb/issues/411
https://github.com/decred/dcrweb/issues/410
https://github.com/decred/dcrweb/issues/409
https://github.com/decred/dcrweb/issues/408

**Comment by jholdstock** [comment]
New website copy is here: https://github.com/decred/dcrweb/pull/762/files Added to github in a temporary directory so it can be reviewed and collaborated upon.

So yes, I think this issue can now be closed. Will review some of those others too and close if possible.
