### ISSUE TITLE
Copywriting request: Update onboarding tour

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#409]
The onboarding tour is rather dated, as it's largely the same since the initial release of the site. 

The tour is essentially intended as a wrap-up of the key topics surrounding DCR and it's use cases. It should avoid turning into very technical or too lengthy, as that's the role of docs.decred.org 
Instead rely on references to docs and other subpages. 

The tour needs considering a somewhat variety of users and use cases: from average people with little to no crypto-experience, regular cc users, organizations, businesses

The design pattern will stay the same, but each point can receive new accompanying visuals. 

The work needs to start by mapping out the key issues and agreeing on a new general structure (or changes to the current). 

Considerations: 
- Textual content should be broken into short and concise pieces and take use of the structure it's housed in (w/ main and sub items.) 
- Wallets can get more comprehensive now, phasing out mentions of webwallet rather referencing to Decrediton and third-party wallets in the Downloads subpage. 
- Consider adding more items describing the use cases of the wallets. 
- A category for Governance and an item for Politeia needs to be added. 
- Planned features imo can be removed as it repeats the roadmap subpage. Rather reduced to reference within another item. 
- Can consider adding an item for Contributing to the project. Ref. to the recruitment post. 
- Mining needs to be re-worked, Staking brought out separately, providing insight to 3 different types of voting.  
- Consider relations to the Governance subpage. 
- Consider relations to the Staking subpage and Decreditons onboarding. This is the furthest out point of engagement, should not get too technical about how tickets exactly work, how to setup wallet, etc. 
- Sync up with proposed language changes. 

Reference materials: Decrediton onboarding slides, Decred booklet. 

Request for involvement #writers-room: Richard-Red, Jazzah

**Comment by dajohi** [comment]
@alexlyp says close
