### ISSUE TITLE
Additional content for the Principles section.

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#411]
Currently the project principles section (in the landing page) covers the following topics: 

```
Free and Open-Source Software
All software developed as part of Decred shall be free and open source-software.

Incremental Privacy and Security
Privacy and security technology shall be implemented on a continuing and incremental basis, both proactively and on-demand in response to attacks.

Free Speech and Consideration
Everyone has the right to communicate opinions and ideas without fear of censorship. Consideration shall be given to all constructive speech that is based in fact and reason.

Multi-Stakeholder Inclusivity
Inclusivity represents a multi-stakeholder system and an active effort shall be maintained to include a diverse set of views and users.
```

I propose for two additional items be added here. 

Firstly Privacy and Security to be broken into separate items. The projects "Security First" approach on different fronts is something well worth highlighting and the stance on Privacy could likely be a bit more informative. I think right now there's an impression the "Incremental Privacy" references to the future privacy feature implementation rather than what's the fundamental stance on privacy for Decred?

Secondly I propose adding something like "Decentralized Launch Distribution" or something simple relating to the "Airdrop". This is an extremely valuable point for many and has been undercommunicated imo. Esp. considering the whole 2017 ICO's case 

Thirdly something to think on: "Multi-Stakeholder Inclusivity" is a very obscure and difficult term. Have noticed in feedback this is simply not understood. I recommend this to be brainstormed over, perhaps a simpler term to communicate the matter can be crunched out. 

Requesting for writers to pitch in here. 

Concept draft: 
<img width="1230" alt="screen shot 2018-10-24 at 15 37 31" src="https://user-images.githubusercontent.com/17774057/47430692-c257ae00-d7a2-11e8-8609-41182380841a.png">

**Comment by Dustorf** [comment]
In my research, I identified the following as core principles:
1) Free and open source software
2) Free speech and consideration, yet meritocratic
3) Evolving, progressive, autonomous stakeholder decision making
4) Privacy & Security
5) Fungibility
6) Decentralization (P2P, anti-rent seekers)
7) Excellence in engineering
8) Deliverables before hype
Privacy and security can be separated. I left them together because that's how they started and I already had 8 points

**Comment by RichardRed0x** [comment]
My first thought about these principles is that they should align with the constitution. Maybe this should be accompanied by a broader community discussion about amending the constitution (which needs to happen to remove out-dated aspects like councils anyway). The discussion and choice of which principles to adopt and prioritize is a good one to engage the broader community in I think.

**Comment by Dustorf** [comment]
I love that idea! That's definitely the way to go about solving this issue. Want to create a channel in Matrix to hash it out? Perhaps you can make an announcement in other channels to invite people to join in the process. Once consensus is reached in the channel, we can make a Pi proposal to ratify it. Thoughts?

**Comment by alexlyp** [comment]
Closed. Since new site.
