### ISSUE TITLE
Serve the site also from decred.bit for better decentralization

### ISSUE THREAD

**Issue by karakozov4** [decred/dcrweb#417]
As you probably know .bit is a top-level domain which controlled by people on Namecoin blockchain. It would be great to serve the site also from decred.bit for better decentralization of the project.

**Comment by ZeroASIC** [comment]
This would involve spending funds out of the dev fund so it should probably be a proposal in Politeia.  Pricing information is here: https://wiki.namecoin.org/index.php?title=Register_and_Configure_.bit_Domains#How_much_does_it_cost

**Comment by jholdstock** [comment]
@dajohi as the site admin you should probably review this one.

I would suggest we close this issue and the author should create a proposal on https://proposals.decred.org if they wish to pursue this further.
