### ISSUE TITLE
Error 404 page

### ISSUE THREAD

**Issue by dajohi** [decred/dcrweb#418]
Create a single standard Decred branded 404 page to be used on all the various *.decred.org sites, complete with embedded css, images, etc. :)

**Comment by linnutee** [comment]
Referring, https://github.com/decred/dcrdesign/issues/80 @rmykolas on this.

**Comment by rmykolas** [comment]
@dajohi the html file for the 404 is done, how should I push it to the repo though?

**Comment by peterzen** [comment]
@rmykolas please add it into `src/404.html` and change the `ErrorDocument 404` line in `runtime/httpd.conf` to reference `/404.html` so that the web server can pick it up.
