### ISSUE TITLE
Get Involved Page

### ISSUE THREAD

**Issue by ZeroASIC** [decred/dcrweb#423]
This is in reference to the discussion going on in politeia issue 747: https://github.com/decred/politeiagui/issues/747

I think it would be appropriate to add something to decred.org that contains some information for new users about getting involved and links to some of the existing and future content on the subject, but it shouldn't replace the existing content entirely.

**Comment by ZeroASIC** [comment]
I'm going to start a draft of this using the document created by @RichardRed0x

**Comment by ZeroASIC** [comment]
Here's a screen shot of my first draft of the page.  I'll add a branch for it in my fork later today.
![screenshot_2018-10-31_12-09-21](https://user-images.githubusercontent.com/4195716/47805871-5fb46400-dd06-11e8-8422-77d69c1fb250.png)

**Comment by ZeroASIC** [comment]
Here's the branch I just made for this issue. https://github.com/ZeroASIC/dcrweb/tree/getinvolved

**Comment by RichardRed0x** [comment]
"Get Involved" sounds like a good title.

There are some aspects that should be discussed and decided, like whether a page like this should be just about work opportunities or whether we need a more general-purpose community-listing space. The github list I made which you refer to is similar to this but not entirely the same. We also discussed a community-maintained list of merchants accepting Decred. We've also been talking about and working on a list of articles/media about Decred, and a list of articles/media produced by Decred contributors.

For me, the question is where do these kinds of community-pull-request-maintained lists fit in on decred.org? It is quite distinct from the pages of decred.org now, but I think it could work if there was a clearly marked space for it.

**Comment by ZeroASIC** [comment]
I think it's more visible if we have a page that at least links to those resources.  I can add new pages as we need them, I just need copy for the page.  More content on decred.org makes more sense than less content, but the main portion of the each piece that you've brought up can exist somewhere other than decred.org.  A little bit of text and some links can go a long way for a new user.

**Comment by xaur** [comment]
> For me, the question is where do these kinds of community-pull-request-maintained lists fit in on decred.org?

Under some "Community Research" heading, why not.

I like "Get Involved" too but I suggest to define its scope. The downside of "Get Involved" is it is abstract. If I'm a merchant accepting Decred, am I involved? If I'm an investor? You get the idea.

**Comment by RichardRed0x** [comment]
That's the kind of page I had in mind for decred.org too.

With GitHub's pages it is trivial to turn a .md file in a repository into a .html with some basic styling. We just need a page on decred.org that lists these community-maintained repositories along with a short description of what each one is for.

**Comment by linnutee** [comment]
I'd recommend to hold horses on this one. Agree on the idea, however as a dedicated subpage this will be conflicting to the subpages planned/in backburner that would cover the same function. 

Firstly once a CMS implementation allows for an easy to manage news subpage, these kind of smaller requests, opportunities or however they're called for getting involved can be actively communicated in a separate news subcategory. E.g: Posting a reference to some specific issue and adding "help needed for this". 

Secondly there is a dev subpage on the backburner, which as one part will highlight key repos with the intent of attracting more contributors. 

Meaning this page will become obsolete once those go up. 

The kind of static repo listing can live in github or dcrdocs instead for now. 

<img width="1011" alt="screen shot 2018-11-01 at 16 02 58" src="https://user-images.githubusercontent.com/17774057/47856485-06286400-ddf0-11e8-8429-35f3d9f91c28.png">

<img width="541" alt="screen shot 2018-11-01 at 16 10 20" src="https://user-images.githubusercontent.com/17774057/47856765-a5e5f200-ddf0-11e8-82d5-873423a5f2b8.png">

**Comment by xaur** [comment]
> Firstly once a CMS implementation allows for an easy to manage news subpage

Will the CMS offer Git-like immutable history?

**Comment by ZeroASIC** [comment]
> > Firstly once a CMS implementation allows for an easy to manage news subpage
> 
> Will the CMS offer Git-like immutable history?

I could answer most of these sorts of questions if I knew CMS it's going to be.  Which CMS is it?

**Comment by s-ben** [comment]
I might suggest adding some of this content to a new page on [dcrdocs](https://docs.decred.org/). Currently, the only pages we have on dcrdocs (which may be some people's entry point to the project) relate to contributing code. This gives the impression that the only way to contribute is by writing code. 

![image](https://user-images.githubusercontent.com/1634777/48918409-25d80880-ee41-11e8-9b33-3a61b7bb7b9a.png)

We could just create a new, simple page that perhaps reuses some content from @ZeroASIC 's first draft posted above. It could be as simple as an intro paragraph and a list of possible projects to contribute to--along with text that lets people know **this is just a sample of possible projects to work on**, here's a link to other resources (decred github, more fleshed out decred.org page when it launches). 

P.S. not to add more orphaned content/plans to this, but when I first came on, I was tasked with working on developer docs. It's still on my to do list, but the project has stalled due to the originator of the project becoming busy with other things. If this gets built, we should include it in our content strategy. Even if it doesn't get built (in current form anyway), here is a page with some content helping developers pick a project to contribute to. 
https://coreynwops.gitlab.io/decred-dev-docs/getting-started/picking_a_project/

**Comment by ZeroASIC** [comment]
@s-ben There is a draft document located here: https://github.com/RichardRed0x/decred-on-github

**Comment by ZeroASIC** [comment]
New Screenshot
![screenshot_2019-01-24_16-59-18](https://user-images.githubusercontent.com/4195716/51714170-081e4f80-1ffa-11e9-84d4-f2383635d9e6.png)

**Comment by noahpierau** [comment]
FYI: we also have https://github.com/decred/dcrdocs/issues/784

**Comment by xaur** [comment]
Get Involved (as shown on the screenshot) is like a map of "where" to contribute, while the doc page that is being built tells "how" to join and contribute. They could link to each other.

**Comment by RichardRed0x** [comment]
Yes, linking them together is a good idea.

In the "Get Involved" content my original intention was that people who know about the software repos would add a sentence or so saying something about the repo and how to get started. Maybe that's not necessary, and a general sentence linking to the docs page is better.

I will do a review of the PR.

**Comment by ZeroASIC** [comment]
This could potentially be two pages.  One with how to join and contribute based on decred/dcrdocs#784 and the other with the current list of things to contribute to.

**Comment by xaur** [comment]
How about reframing it as `/contribute` page?

Example: https://about.gitlab.com/community/contribute/

**Comment by jholdstock** [comment]
Closing this issue as we have covered the topic quite extensively:

https://docs.decred.org/contributing/overview/
https://docs.decred.org/contributing/contributor-compensation/

https://devdocs.decred.org/projects/
https://devdocs.decred.org/contributing/contributor-guidelines/
