### ISSUE TITLE
DEX is presented as Planned Feature

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#432]
The "Planned Features" block on the [root page](https://decred.org/) includes "Decentralized exchange". u/oneeyedfalcon [raised](https://www.reddit.com/r/decred/comments/9t697o/why_is_the_decentralized_exchange_listed_on_the/) a concern this may (ab)use the website to (or be perceived to) create community bias prior a politeia vote.

I think the root cause is the copy is simply not accurate. On the [roadmap](https://decred.org/roadmap/) page this item is presented more clearly as "Proposal For a Decentralized Exchange" and "The project will be formalized as a Politeia proposal.".

In my view this is a valid concern since the DEX is quite distinct from all other points presented as Planned Features: it requires a Politeia vote and a team to step up and take the work. In some sense it is "optional" to the project roadmap (although not sure the word is right).

**Comment by ZeroASIC** [comment]
Maybe I should add something about "pending approval of a proposal" to it.

**Comment by xaur** [comment]
"Proposal for a Decentralized Exchange from" is quite good. Proposal is indeed planned, while the DEX itself is not planned until approved.

**Comment by ZeroASIC** [comment]
This section looks like it could use a few more updates.  "SPV wallet support" is complete and so is "Politeia voting".  Those were the first two on the list, but I just removed them.  Alternatively I could denote that they have been completed.  I moved "Proposal for a Decentralized Exchange" to the bottom.

**Comment by xaur** [comment]
@dajohi is there a way to know when is the next deployment that includes this fix? I'd like to update the person who reported the issue.

**Comment by ZeroASIC** [comment]
Closed in #441
