### ISSUE TITLE
List of PoW pools

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#433]
The sites has a nice list of PoS pools (to be renamed to VSP) with advanced columns.

How about a similar list for PoW pools?

**Comment by xaur** [comment]
The list of VSPs is pulled from a server that runs code from dcrwebapi repository. Some data like name and launch date is hardcoded, while the other is dynamic. I don't know how dcrwebapi obtains it and wonder if it could do the same for PoW pools. This could actually be beneficial if it did: the _pools_ will be interested to get listed, would contact us and this would lead to us having more complete picture of the pools.

**Comment by ZeroASIC** [comment]
It pulls VSP info from this URL https://api.decred.org/?c=gsd
We could add the PoW pools to the API and have it return data in the same fashion.

**Comment by dajohi** [comment]
Please open an issue/feature request at https://github.com/decred/dcrwebapi

**Comment by ZeroASIC** [comment]
https://github.com/decred/dcrwebapi/issues/52

**Comment by alexlyp** [comment]
PoW mining is pretty specialized I don't see value for the average person knowing what the pools are. Closing.  If this is deemed vital we can reopen in reference to the new site.

**Comment by xaur** [comment]
Specialized is a good point. List of VSPs is useful for end users while list of PoW pools is not. I think it's still nice to have, but should live elsewhere.

**Comment by jholdstock** [comment]
Available in dcrdocs 

https://docs.decred.org/mining/overview/#sign-up-for-a-mining-pool
