### ISSUE TITLE
Inconsistent Error Message and Odd "testpool" with 46% of votepower

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrweb#436]
For the first time this morning I started getting this error when trying to load the page on mobile (latest iOS, similar error with Firefox and Safari):
![photo_2018-11-10_11-55-24](https://user-images.githubusercontent.com/4402603/48305463-a7de3e00-e4df-11e8-8b46-2e5b3ae3702a.jpg)

Also, there is a pool listed as teststakepool.decred.org with 46%:
![photo_2018-11-10_11-55-06](https://user-images.githubusercontent.com/4402603/48305464-ac0a5b80-e4df-11e8-862f-ff1cf80eefe7.jpg)

**Comment by ZeroASIC** [comment]
So far I con't reproduce your error, it might be iOS specific. I do see the testnet pool though and it looks like it supposed to be styled differently, but for some reason it isn't.  I can fix the styling or filter it out.  The raw data is located at this URL https://api.decred.org/?c=gsd

**Comment by oregonisaac** [comment]
Actually I can't reproduce the error right now either.  I tried multiple browsers and got the error for a couple minutes before posting.

**Comment by oregonisaac** [comment]
Getting the error again this morning.  Here’s how it looks in Firefox.
“Resource unavailable”
[TRY AGAIN]

A refresh or two gets me to the page.

**Comment by ZeroASIC** [comment]
I shut off the networking to my VM and I still can't reproduce this error.  It looks like it's generated by Firefox and not our code.  It doesn't look like it's a problem with api.decred.org either.  It might be a connectivity issue, but that doesn't mean the problem is your browser or your computer.

**Comment by dajohi** [comment]
@oregonisaac please reopen if this is still occurring.
