### ISSUE TITLE
Remove references to web wallet

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#438]
Web wallet is deprecated and will soon be taken offline. We should not be encouraging people to use it.

decred/dcrdocs#695 removes references to the web wallet from the documentation. It might be time to do the same on decred.org.

Currently we have this on the landing page, I havent checked if there are any more appearances:

![wallet](https://user-images.githubusercontent.com/6762864/48440212-3244cd00-e780-11e8-946e-d1a95a9c136a.png)

**Comment by ZeroASIC** [comment]
I could remove it really fast, I just did actually, but it looks a little bit empty now.  I think we should add something about Decredition in it's place.

**Comment by ZeroASIC** [comment]
Rewording it helps a bit:
`Decrediton is a cross-platform GUI wallet for Decred. Available for Windows, MacOS, and Linux users.`

**Comment by jholdstock** [comment]
#440 doesn't really close this issue. There is still some things left to do:
- we still have a webwallet.svg file
- webwallet is still mentioned in .css files
- still appears in .po/.pot files. To be honest I'm not sure if we need to update these or not, I am not very close with the translation framework

I also think its worth mentioning our CLI wallet in the section I posted in the screenshot above. Decrediton is not the only wallet

**Comment by ZeroASIC** [comment]
- I just removed the image and the CSS.
- The Translations are way off in some areas as noted in #210 and I'm not well versed in it either.
I can add something about the CLI wallet.  Do you have any suggestions?  Feedback is always appreciated.

**Comment by ZeroASIC** [comment]
How about
`Command-line wallet and utilities are also available for a variety of platforms for those that prefer it.`

**Comment by ZeroASIC** [comment]
Closed in #445
