### ISSUE TITLE
Remove testnet pool from stakepools list

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#446]
It is confusing to have testnet stakepool in the table together with all the mainnet stakepools. I always felt it deep inside of me, but finally hypernoob expressed it in words [in #support](https://matrix.to/#/!dhHYPTtCtvPSUfTepT:decred.org/$154190872313089GfuSM:decred.org).

**Comment by xaur** [comment]
That would be even better. There needs to be a better place for developers and service providers to learn about the test pool. Perhaps dcrdocs.

**Comment by ZeroASIC** [comment]
This could be removed from the dcrwebapi instead of the website.  I could filter it out on the website, but it makes more sense to remove it from the data the API returns.

**Comment by xaur** [comment]
Good point, created an issue there.

**Comment by alexlyp** [comment]
Right just remove from the list, it's used from the api.

**Comment by ZeroASIC** [comment]
> Right just remove from the list, it's used from the api.

So I can just filter it out on the website and the issue for dcrwebapi can be closed?
