### ISSUE TITLE
Downloads: emphasize signature verification

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#476]
https://decred.org/downloads/

> If you are downloading the Decred binaries, please follow these Binary Verification steps to verify the **checksums**.

a little reminder about digital signatures won't hurt, something like

> Please verify digital signatures of the files you download. This is the only way to make sure they come directly from the developers without modification by middlemen.

**Comment by peterzen** [comment]
+1 for this.  Also, it would be good to have the binary checksums published not only on the GH download page but also on decred.org?

**Comment by xaur** [comment]
At least release keys and signatures, sure. Going further, binaries could also be self-hosted.

**Comment by alexlyp** [comment]
We already have instructions to verify binaries and have those sigs hosted and committed in a repo.  Don't think we need to put on the main site.

**Comment by xaur** [comment]
I see the text was improved:

> For the security conscious, please follow these instructions to verify the Decrediton and Command-line app suite binaries.

I wouldn't mind a bit stronger wording but this is ok.
