### ISSUE TITLE
Design bug (text not showing)

### ISSUE THREAD

**Issue by lemonkabir** [decred/dcrweb#480]
Hey,
there have a bug.it's should fixed up
It's fully like my previous report.Just location changed.
Vulnerable parameter : https://www.decred.org/stakepools
See at top paragraph for responsive design and also for responsive header it's not showing.I mean some text showing.

Thanks

**Comment by degeri** [comment]
Please don't use words like "Vulnerable parameter : " for visual/design bugs.

**Comment by lemonkabir** [comment]
sorry for that

**Comment by ZeroASIC** [comment]
This is a duplicate of #479.  Please don't start new issues for the same problem on multiple pages, they should all be listed in one place.
