### ISSUE TITLE
for responsive design (design bug)

### ISSUE THREAD

**Issue by lemonkabir** [decred/dcrweb#481]
Hi,

in your this url: https://www.decred.org/roadmap
when u scrolling down then see the option bar are coming down and create a problem to see some text.
![1de](https://user-images.githubusercontent.com/40144795/50703000-e0803b00-107c-11e9-8b19-3c4c6a97ea03.JPG)
![2 dec](https://user-images.githubusercontent.com/40144795/50703003-e249fe80-107c-11e9-88c4-30c357da60cf.JPG)
as a responsive design it should fixed it

Thanks

**Comment by rmykolas** [comment]
I believe this is intentional by design, so the issue can be closed.
