### ISSUE TITLE
Replace Slack invite page

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#482]
Slack has added the ability to create invite links that do not expire. It seems we can now simplify the current process which involves a bot sending email addresses to a private channel where some of us manually process invites. With the link below a user can join Slack without any manual intervention on our part.

https://join.slack.com/t/decred/shared_invite/enQtNTE4MDM1NzAzODEzLTdhYzM4NDIwNDJmNDFkODViYjFhYzc1MDY5N2FmZjY3MGQ2NTY3ODA1MmYxMDdhYTYxMTc4MjY5NDI4Y2JkNmQ

**Comment by ZeroASIC** [comment]
This is great.  I actually started an updated landing page in #462 with the new matrix landing page.  Once that gets merged in I can finish up the new landing page with this link.

**Comment by jzbz** [comment]
I think the best solution might be to create a redirect from https://slack.decred.org/ to the new URL, that way the old links don't break and if we need to revert we can just kill the redirect. @dajohi does this make sense?

**Comment by dajohi** [comment]
Implemented.
