### ISSUE TITLE
Easyrabbit exchange is an instant exchange but tool tip suggests High liquidity

### ISSUE THREAD

**Issue by dezryth** [decred/dcrweb#488]
Small issue, just thought I'd point it out. The icon is for instant exchange, yet the tool tip suggests high liquidity. See image below:
![capture](https://user-images.githubusercontent.com/5300356/51076790-f84e5500-1662-11e9-9754-cc22d20607ee.PNG)

**Comment by peterzen** [comment]
Fixed in #510

**Comment by peterzen** [comment]
This can be closed now @dezryth
