### ISSUE TITLE
Add Matrix Contributor credentials and audit contributor chat preference

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrweb#499]
Firstly we should add the ability to add matrix contact credentials.
For example,
https://matrix.to/#/@jrick:zettaport.com

And we should contact each contributor to see if they'd like their slack icon removed and a matrix one added in it's place.

Jrick and ay-p would like that for sure.

**Comment by peterzen** [comment]
Prepped this in https://github.com/peterzen/dcrweb/pull/2

Will open a PR once the Hugo stuff gets merged into `dcrweb:master`
