### ISSUE TITLE
for responsive design (design bug)

### ISSUE THREAD

**Issue by lemonkabir** [decred/dcrweb#500]
Hey

I think there have a designing bug that's why some text are not showing in screen.
Url : https://www.decred.org/press

Thanks

**Comment by peterzen** [comment]
Could you share a screenshot with more details?

**Comment by peterzen** [comment]
This sounds like a design issue for @linnutee - maybe something to consider in the current Press section redesign.

**Comment by linnutee** [comment]
Not so keen on things like the navigation being changed on a whim. If this is regarding the nav overlap, issue can be closed. The nav box overlap does not occur in any instance, where it would block the content in a critical manner e.g. one couldn't scroll further.

**Comment by dajohi** [comment]
@lemonkabir please reopen if you are not satisfied with @linnutee's response.
