### ISSUE TITLE
Content spoofing 

### ISSUE THREAD

**Issue by lemonkabir** [decred/dcrweb#531]
Hey
There have content spoofing issue.Please fix it.For identifying please check my enclosed attachments.
1st for request 

![server 1](https://user-images.githubusercontent.com/40144795/51863200-a0a23000-236a-11e9-80f4-59f9368fb606.JPG)

2nd for response

![server 2](https://user-images.githubusercontent.com/40144795/51863235-b152a600-236a-11e9-9a0c-fe9659ffa22c.JPG)

Thanks

**Comment by dajohi** [comment]
Wrong repo.

**Comment by ZeroASIC** [comment]
> Hey
> Why ?

If the error is on docs.decred.org then the issue needs to go in their github repo instead of this one.

**Comment by lemonkabir** [comment]
Then where should i create one ?
