### ISSUE TITLE
External nav items - open as tabs

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#535]
This seems to have been changed at some point, the external such as docs, politeia, dcrdata should open as new tabs rather than in being directly linked. 

Also bringing up the the case regarding creating a "re-direction notice" that should be applied for referring to third-party pages as a reminder about responsibilities to the user.

**Comment by peterzen** [comment]
1 downvote for the redirection notice - all it does it break the user flow and with the external page now opening in a new tab it's sufficient indication. 

Where such notice would make sense from a potential legal liability perspective is the Exchanges section that indeed has links to external parties which we have no control over, and which directly handle funds.  Alternatively, in the interest of keeping a smooth user flow, a standard boilerplate notice at the top of the page stating that Decred is not endorsing any of the listed services in no way responsible for any potential loss of customer funds yadda yadda.

**Comment by xaur** [comment]
I don't see a need for redirection notice either. It is necessary on Politeia, but decred.org is just an info website with no accounts.
