### ISSUE TITLE
Turkish TR Translation Issues - https://decred.org/tr/

### ISSUE THREAD

**Issue by oregonisaac** [decred/dcrweb#544]
The following is feedback from community member Seyf:
1. when you tap on the menu icon, you'll realize that some items are not translated
2. "Indirmeleri" should be "Indirmeler" or "Indirme Dosyaları"
3. %100 kanıtlanmış açık kaynak teknolojisinden oluşturulmuştur.. has an extra stop at the end of the sentence
4. In the landing page, the section Platform has a translated title, followed by an untranslated text, and some translated list items
5. "Lightning Network gibi işe yarayan akıllı sözleşmeler" is poorly translated. It should be "Lightning Network gibi çalışan akıllı sözleşmeler"
6. "This tour will help you get started with Decred" section is a mess. One sentence is translated, but the one comes after it is not. Similarly, more than half of the items in this section are not translated.
7. Clicking on Press in the footer opens the 404 Page "https://decred.org/tr/press/"

**Comment by Soyseyf** [comment]
Hey Peter, this is Seyf. Can you give me access to the localization tool, please?

**Comment by oregonisaac** [comment]
I talked to Seyf, they would like access, connect directly here: https://t.me/SminusO

**Comment by peterzen** [comment]
Hey @Soyseyf, did you get a chance to make the changes in Transifex?

**Comment by dajohi** [comment]
@Soyseyf ping

**Comment by alexlyp** [comment]
Outdated due to new site.
