### ISSUE TITLE
Community page wechat contact update 

### ISSUE THREAD

**Issue by changhugo** [decred/dcrweb#552]
The current contact for wechat is Bill, but I am not sure if Bill is active. Nobody has been added to the Decred wechat group through Bill in the past couple months. 

Spoke to Guang and he agrees to serve as the contact. 

Guang’s Wechat username is DecredGuang

**Comment by Guang168** [comment]
Noticed @karamble added previous images on #381 with the words on images. Wonder if he still has the original file and easier to edit the username to `WeChat: DecredGuang`
