### ISSUE TITLE
voting.decred.org - show dates/blocks for past votes and approval %

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrweb#559]
I think the voting.decred.org page would be improved by adding dates (and block numbers) for when the votes started/ended/activated.
Also, I think the page should express the voting outcome as an Approval % as used to determine the 75% cutoff - so [Yes]/[Yes + No]
This would be in addition to the Yes, No, & Abstain figures currently reported, which are useful but perhaps slightly confusing because they differ to the criteria which are used to determine success.

**Comment by dajohi** [comment]
this belongs in the https://github.com/decred/hardforkdemo repo. (voting website)
