### ISSUE TITLE
Add ditto contractors 

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#562]
Noticed they never got added, though the portraits are done. Get them here for Liz Bagot, Margaret Huang and Milvian as well the company logo (which should be indicated for each profile) [dcr - ditto assets.zip](https://github.com/decred/dcrweb/files/2881099/dcr.-.ditto.assets.zip)

@jzbz or @Dustorf should have the details, can drop here – didn't find any mentions on slack/riot.

**Comment by jholdstock** [comment]
I can implement this

**Comment by Dustorf** [comment]
Jamie-thanks for picking this up. 
Margaret Huang
https://www.linkedin.com/in/margarethuang/
Matrix: margaret_mei


Liz Bagot
https://www.linkedin.com/in/elizabethbagot/
Matirx: liz_bagot
Twitter: @liz_bagot

Milvian Prieto
https://www.linkedin.com/in/milvian/
Matrix: milvian
Twitter: @MilvianPrieto
