### ISSUE TITLE
Move contact info onto Matrix where possible

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#567]
Many contributors have moved onto Matrix as their primary comms platform, but `/contributors` has not been updated accordingly. Additionally, there are many broken slack links on the page.

**Comment by jholdstock** [comment]
**Left to do after the above PR:**

- macsleven
- collins
- klka
- kart
- papa_carp
- rmykolas
- Nick
- rogueelement
- sndurkin
- oktapodia
- vctt
- Maria
- lindseym
- timhebel
- sef
- bill
- DZ
- butterfly
- Jesiki
- mm
- nkpla
- oregonisaac
- trace

**Comment by jholdstock** [comment]
Outstanding after the previous PR:
- Nick
- sef
- bill
- Jesiki
- nkpla
- oregonisaac
- klka
- mm
- sndurkin
- Maria

**Comment by jholdstock** [comment]
Left todo:
- klka
- sndurkin
- sef
- Jesiki
- mm
- nkpla

**Comment by jzbz** [comment]
Sef is `@sefbkn:matrix.org`

**Comment by jholdstock** [comment]
@sndurkin:matrix.org

**Comment by jholdstock** [comment]
@mmartins:matrix.org
