### ISSUE TITLE
Menu item has changed

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#569]
I'm pretty sure this used to be formatted "Block Explorer" 

![screenshot from 2019-02-20 10-49-15](https://user-images.githubusercontent.com/6762864/53086593-4de90d80-34fd-11e9-92e9-ae81085a1089.png)

**Comment by jholdstock** [comment]
@peterzen is this related to translations?

**Comment by peterzen** [comment]
Not sure - I recall this was in the issue requesting the change verbatim.  Changed in #574
