### ISSUE TITLE
add links to subdomain of decred.org at frontpage

### ISSUE THREAD

**Issue by zhizhongzhiwai** [decred/dcrweb#575]
could add links to subdomain of decred.org at frontpage??
subdomain includes: bounty; voting; proposals; time(or rename to opentimestamp); mainnet; testnet;

**Comment by xaur** [comment]
Note that mainnet.decred.org (Insight explorer) will be discontinued in favor of dcrdata.

**Comment by noahpierau** [comment]
Agreed, it makes sense to link to https://bounty.decred.org/ on the frontpage or the menu.

It seems that voting, proposals and mainnet explorer are already listed.

**Comment by jholdstock** [comment]
@dajohi  I think we can close this one

**Comment by jholdstock** [comment]
nm, I have permissions.
