### ISSUE TITLE
Add Cryptofacil to exchanges list

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#586]
URL: https://cryptofacil.com/
Logo: https://v.fastcdn.co/u/dccddcff/34937656-0-logo-white.png

**Comment by 3lian** [comment]
Hi, just a detail, at the moment Cryptofacil does not support Fiat (in https://decred.org/exchanges/ is mark as Fiat ramp), however, it could be mark as High Liquidity because they share Bittrex books.
