### ISSUE TITLE
Enable Github-Transifex integration

### ISSUE THREAD

**Issue by peterzen** [decred/dcrweb#591]
TF now has GH integration which lets us sync the translation file directly without the need of the error-prone manual uploading of the changes: https://docs.transifex.com/integrations/transifex-github-integration

This would be useful to have in order to avoid the problems we've had in the past when changes in `dcrweb` got lost/overwritten by edits in TF.

Link for configuring TF access to the dcrweb repo: https://www.transifex.com/decred/dcrweb-hugo/settings/integrations/

**Comment by johncodesit** [comment]
@peterzen  is this still an issue? TF URL is broken

**Comment by comradekingu** [comment]
Transifex is still prone to it.
Consider https://docs.weblate.org/no/latest/admin/continuous.html?highlight=webhooks#automatically-receiving-changes-from-github :)

**Comment by jholdstock** [comment]
We no longer use transifex, closing this issue

**Comment by comradekingu** [comment]
@jholdstock Have you set up shop on a different platform?
