### ISSUE TITLE
Add TLSA DNS record for decred.org

### ISSUE THREAD

**Issue by peterzen** [decred/dcrweb#592]
Pin the decred.org TLS certificate to the DNS using DNSSEC:
 
https://blog.apnic.net/2017/01/06/lets-encrypt-dane/

This would protect *.decred.org sites against a class of MitM attacks:

https://security.googleblog.com/2015/03/maintaining-digital-certificate-security.html

attn @dajohi

**Comment by johncodesit** [comment]
@dajohi @peterzen  is this still an issue? looking for my first good issue. Thanks :)

**Comment by peterzen** [comment]
Not getting any attention, closing.
