### ISSUE TITLE
Incorrect icon for "Cryptofacil" on exchanges page

### ISSUE THREAD

**Issue by 3lian** [decred/dcrweb#608]
"Cryptofacil" is marked with the Fiat icon, however Cryptofacil does not support Fiat (in https://decred.org/exchanges/ is mark as Fiat ramp), it could be mark as High Liquidity because they share Bittrex books. They offer the pairs DCR/BTC and DCR/USDT.

**Comment by peterzen** [comment]
The exchange does offer a fiat onramp though (through Visa/MC) - shouldn't it have both tags?

**Comment by 3lian** [comment]
You're right. I think both tags is appropriate then.
