### ISSUE TITLE
background animation on landing page does not scroll

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#610]
The left "Decred" panel scrolls up as expected, however the mining animation on the right panel does not, it seems to have a static position:

![Screenshot from 2019-03-19 05-24-05](https://user-images.githubusercontent.com/6762864/54582089-5dc61580-4a07-11e9-974e-893dcbeaea1e.png)

![Screenshot from 2019-03-19 05-24-17](https://user-images.githubusercontent.com/6762864/54582091-5ef74280-4a07-11e9-8b6c-0c47a3c1940e.png)

**Comment by peterzen** [comment]
I think this is a feature, not a bug.

**Comment by jholdstock** [comment]
It looks a little funny to my eye, I would expect it to scroll with the rest of the page. This issue can be closed if it is intended behaviour

**Comment by karamble** [comment]
i also think it is intended parallax behaviour

**Comment by linnutee** [comment]
Yup so it was. Don't recommend doing much tweaking around the landing page at all, as there's an overhaul for it in the pipeline already.
