### ISSUE TITLE
Change the logo hover text

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#615]
Hovering over the main Decred logo on the homepage shows a sub-text "decentralized CREDIT". We should change this to "decentralized CREDITS" (with additional s).

The same change needs to happen on the /brand page.

Decred is a great name with an excellent [origin story](https://thedecreddigest.com/2017/09/01/decred-behind-the-name/), but people sometimes seem to struggle with it. 

We agreed in #marketing that using "decentralized credits" in our messaging will help people get used to the name. Related issue - #66 - mentioned it would make a nice addition if the sub-text was **shown all the time**, but this is a design decision.

**Comment by linnutee** [comment]
If this seems to be an issue – can grab a well kerned version of the decentralized credits from here https://github.com/decred/dcrdesign/issues/76. 

Or better – remove it altogether ;)

Regarding #66 of showing the hover all the time. The "decentralized credit" reference in hover was only designed as an easter egg to accompany the launch of decred's identity in the very first release of dcrweb by EETER. This was driven by the context, as at the time the site had little content (being the initial one-pager release in late 2016/early 17) and all of Decred's branding and comms output was right out of the oven and with little depth and solidification so to say. Now it's been almost 3 years, this decentralized credits bit has had basically no use at all. Besides that easter egg riding through the updates, there is a single motion design asset which Justin requested. However I don't think it even got used anywhere nor do I see any place for it in the defined visual identity as an asset or logo tagline until a usecase shows itself. Till then more likely it would be competing with other slogans and taglines.

I personally find every time this topic is brought up, it tends to get pushed into touching point of some soft rebrand and essentially making a problem where there isn't one. Decred is the name of the project. This works well and is accepted widely. Decentralized credits is merely the reference for the idea where the name was derived from. People will or won't get used to the name regardless. I don't see for any need for every new user to be required to know that the name is derived from decentralized credits – that's something that might be learned over time as an interesting fact if there's enough enthusiasm, nerdery etc.
