### ISSUE TITLE
Integrating Forum with Slack channel

### ISSUE THREAD

**Issue by gravityz3r0** [decred/dcrweb#62]
Decred forum are not seeing much activity these days and new users may think that we are a "dead" community when in actuality, 95% of the activity happens on slack.

A integration of a "trollbox-like" chat room on top of the forum that connects to Slack will reflect better our current level of activity.

**Comment by xaur** [comment]
A chat window _on top_ of the forum effectively says: forget the forum, use the chat, chat is more active.

Forum is a totally different communication tool, one that allows you to have asynchronous discussions focused on single topic, and not hunt down replies in ever-erasing Slack history.

I really wish the forum was more active as I like reading threads by-topic. But not by breeding with chat.

**Comment by jolan** [comment]
This won't get implemented so I'm going to close it.  Slack is being actively migrated away from and part of the process involves setting up bridges to other chat networks and that the current number of integrations is already very troublesome to maintain.
