### ISSUE TITLE
Header bug on Press page

### ISSUE THREAD

**Issue by denyszayets** [decred/dcrweb#625]
Noticed this bug on Press page of the website. Short video demo https://d.pr/v/LIUjDP

**Comment by vincent-bekir1** [comment]
Hi @denyszayets , I just opened the press page of the website, the header is well aligned.

![image](https://user-images.githubusercontent.com/48955960/55194288-7f629200-51a9-11e9-9646-af150788a665.png)

**Comment by denyszayets** [comment]
When I hover news links it has a glitch on my end. Did you watch my video?


On Thu, Mar 28, 2019 at 17:34, vincent-bekir1 <notifications@github.com> wrote:
Hi @denyszayets [https://github.com/denyszayets] , I just opened the press page of the website, the header is well aligned.

[https://user-images.githubusercontent.com/48955960/55194288-7f629200-51a9-11e9-9646-af150788a665.png]

**Comment by peterzen** [comment]
Apparently there's a Z-fight going on between the video and the tab top layers.  Since there's ongoing work to revamp the News section altogether this probably isn't worth fixing separately.

**Comment by denyszayets** [comment]
No problem, just letting you all know

On Fri, Mar 29, 2019 at 10:06, Peter Banik <notifications@github.com> wrote:
Apparently there's a Z-fight going on between the video and the tab top layers. Since there's ongoing work to revamp the News section altogether this probably isn't worth fixing separately.

**Comment by dnldd** [comment]
spotted the header bug reported for the contributors page as well.
