### ISSUE TITLE
Add new batch of contributors

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#632]
Kärt got another round of portrait illustrations ready for: changhugo, dominic, michael, milvian and thiago.

@jzbz can share the details for each. 

[portraits10_exports.zip](https://github.com/decred/dcrweb/files/3043233/portraits10_exports.zip)

Nb! If any new contributors are looking to be added, send your details and portrait shot according to this guide (https://github.com/decred/dcrdesign/issues/47) over to @jzbz; these are addressed in a batch.

**Comment by jholdstock** [comment]
@linnutee, there seems to be an issue here, Milvian from Ditto is a woman (and she is already included on /contributors https://decred.org/images/contributors/milvian.svg)

The new picture provided seems to be a man. Is there a mixup with the names?

**Comment by jzbz** [comment]
That mystery person is Angelo. I'll get details for all the new people in a bit.

**Comment by jzbz** [comment]
```
[Portrait mistakenly named "Milvian"]
Angel Dominguez
Marketing
@anshawblack:decred.org

Thiago de Freitas Figueiredo
Developer
@thi4go:matrix.org

Hugo Chang
Community Manager (CN)
@changhugo:decred.org

Dominic D
Community Manager (CN)
@dominic.d:decred.org
https://twitter.com/wanbihou

Michael Guimaraes
Community Manager (BR)
@michae2xl:decred.org
https://twitter.com/michae2xl
```

**Comment by Michae2xl** [comment]
I’m so happy about it, thank you so much for each one. Well, just the description sounds wrong (BR), because Emilio is Community manager BR
