### ISSUE TITLE
Logo gets bumped out of view

### ISSUE THREAD

**Issue by gratefulcheddar** [decred/dcrweb#65]
Using Safari on macOS Sierra 10.12.4, when I go manually resize the browser window on my 2560x1080 display, it does this to the logo between 1/3 and 1/2 width:
![screen shot 2017-05-12 at 8 56 15 pm](https://cloud.githubusercontent.com/assets/12915233/26021554/c8949d3a-3755-11e7-9aac-45bcccfcbc18.png)

**Comment by noahpierau** [comment]
New website, this issue can be closed @karamble

**Comment by jolan** [comment]
Closed via #159.
