### ISSUE TITLE
Add link to CN community page

### ISSUE THREAD

**Issue by Guang168** [decred/dcrweb#651]
bottom right corner of https://decred.org/zh/ 

Link : https://www.chainnode.com/forum/305 
Logo : 
![launch icon inverse-02](https://user-images.githubusercontent.com/43533453/57352068-c07d9700-7196-11e9-85ad-36b0bfbf5808.png)

**Comment by jholdstock** [comment]
There may be a wider issue to address here. 

https://github.com/decred/dcrweb/blob/2caa4062e3d0e9e92340600106e4093e81928644/src/layouts/partials/footer.html#L40-L44

https://github.com/decred/dcrweb/blob/2caa4062e3d0e9e92340600106e4093e81928644/src/config.yml#L34-L51

This code makes me think that we should be displaying qq, youku and wechat links on the `/zh` homepage, but I am not seeing those. I am seeing the same social links regardless of language selected.

**Comment by peterzen** [comment]
The links are there but they're missing the qq/wechat icons.  I recall there was an issue requesting the QQ/WeChat icons way back but can't find it ATM.

**Comment by Guang168** [comment]
QQ and wechat icon are in https://decred.org/community/ 

The links for qq and wechat are in correct tho. suggest to remove qq group, not many admins active over there. wechat link under community page is correct. 

I also see same social links regardless of language selected on
1. footer of homepage 
2. footer of hamburger menu on right

**Comment by jholdstock** [comment]
I will pick this up

**Comment by jholdstock** [comment]
@Guang168 
Are there any social media icons which should be hidden on the /zh site? Eg. Youtube?

**Comment by jholdstock** [comment]
I've opened a PR which will fix Wechat, qq and youku. I haven't got time to add chainnode right now.

**Comment by Guang168** [comment]
I see wechat qq and youku is fixed now on main page footer and side bar footer. Any luck with adding chainnode ?
