### ISSUE TITLE
Add Binance OTC to the list of OTC desks supporting DCR

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#653]
Binance logo: https://upload.wikimedia.org/wikipedia/commons/1/12/Binance_logo.svg
Example Binance OTC logo: https://cdn-images-1.medium.com/max/800/1*VSj08NwHn7-WpU7Ex4Gp3w.png

**Comment by jholdstock** [comment]
Is there a proper public URL for this? Eg. something like binance.com/OTC?

All I can find are links to https://t.me/BinanceOTC or instructions to email tradedesk1@binance.com

**Comment by jholdstock** [comment]
We could possibly use the announcement post: https://www.binance.com/en/blog/294786426278453248/Crypto-OTC-Services-Now-Available-on-Binancebinance

**Comment by jzbz** [comment]
@jholdstock yes the announcement post is the only official page mentioning it IIRC. Let's use that.
