### ISSUE TITLE
Where to spend DCR

### ISSUE THREAD

**Issue by jcvernaleo** [decred/dcrweb#67]
People on the documentation survey suggested a (curated) list of places where one could spend dcr.  It was agreed that it is a nice idea, but not really something that belongs on the docs site so closing the issue decred/dcrdocs#261 in favor of this issue since it would make more sense on the website.

**Comment by linnutee** [comment]
What about the legal side of this? Can we recommend or refer to any of those sites or would that create a kind of conflict of interests?  

I recall this was an issue with listing crypto exchanges in the mainsite earlier this year.

**Comment by pvtwarren** [comment]
I listed a couple of exchanges in the r/decred sidebar on reddit, it would seem more appropriate to list them there since r/decred has a less 'official' feel to it

**Comment by dajohi** [comment]
Is this still needed?

**Comment by jolan** [comment]
I think it would be too much of a burden to maintain an official/vetted list.  If anyone really wants this, we can debate it some more when a PR is submitted.
