### ISSUE TITLE
Decred updates - feature - suggestion

### ISSUE THREAD

**Issue by Michae2xl** [decred/dcrweb#684]
Is this could be good to have in somewhere on the dcr website? This is a suggestion like kraken did

https://trade.kraken.com/assets/dcr

![EEC46FC4-6F82-42AF-8FE1-E10A3BD6E9F5](https://user-images.githubusercontent.com/44928059/60623906-e8adfe80-9db1-11e9-9146-054255a80185.jpeg)

**Comment by alexlyp** [comment]
This is covered by the new section, adding a stream from some other source seems like overkill, people can folllow twitter if they want constant content.
