### ISSUE TITLE
Google Plus No Longer Exists, Remove Button?

### ISSUE THREAD

**Issue by Tsunekazu** [decred/dcrweb#699]
I'm not sure if the blog is considered part of dcrweb, but while reading the new blog post : https://blog.decred.org/2019/08/21/Surveying-the-Privacy-Landscape/ I noticed it still has a G+ link, even though Google Plus has ceased to operate (click on the G+ button to see the warning)

**Comment by jholdstock** [comment]
The blog is not part of the dcrweb website, but it's a valid point nonetheless. I don't think the source for the blog lives anywhere public.

I guess this would be one for either @dajohi or @behindtext to fix up, I'm going to close this dcrweb issue for now.
