### ISSUE TITLE
Wrong latest release shown

### ISSUE THREAD

**Issue by kargakis** [decred/dcrweb#7]
https://decred.org/

shows 0.1.3 as the latest stable release but it's not the latest since https://github.com/decred/decred-release/releases/tag/v0.1.4

**Comment by jolan** [comment]
If you see the forum, this is intentional.  I'll leave this open though until I add the unstable release.

**Comment by kargakis** [comment]
How is a release regarded as stable or unstable? So far all releases are pre 1.0 so one pov is that no release is stable. Another pov is that every new release cut from master is stable.

**Comment by jolan** [comment]
It's ad-hoc for the time being.

A lot of syncing from the upstream project btcd is on-going.  Releases are thoroughly tested but with so much code churn, it's difficult to know for sure.

In the near future, we should get to the point where every new release is considered stable.

**Comment by jolan** [comment]
I added the unstable release to the website to make it clearer that we have 2 branches for now.
