### ISSUE TITLE
Links with no effect on https://decred.org/brief/

### ISSUE THREAD

**Issue by al-maisan** [decred/dcrweb#701]
The links in the following sections have no effect:

  * "How is work on Decred organized?"
  * "Decred in Q4 2018"

**Comment by peterzen** [comment]
Can you specify what browser you're using please?

**Comment by al-maisan** [comment]
Firefox 60.8.0esr (64-bit) on debian -- when I hover over the links I see the following URL "https://decred.org/brief/#"

**Comment by peterzen** [comment]
I can't reproduce this on FF 68.0.2 (64-bit) Ubuntu, all links in the outline work correctly.  Just to be clear, are you referring to the outline menu, correct?

![image](https://user-images.githubusercontent.com/5878500/63859683-0c538680-c9a8-11e9-9ac4-cbe77b7b14b7.png)

**Comment by al-maisan** [comment]
What should actually happen when I click on one of these links e.g. "15 contributors"?
