### ISSUE TITLE
Custody wallets: remove or add new section

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#710]
A user mentioned that Cobo only lets you withdraw 41 DCR a day. If you have 200 DCR it will take you 5 days to withdraw your credits. The user also reported that Cobo manually approves your transaction(s), so you will have to wait for them to send your coins. Based on [the Cobo website](https://cobo.com/), it is a company similar to Coinbase. They offer cloud wallets, HD wallets, as well as "custody" services. Their cloud wallet also lets people stake small amounts of DCR to receive a reward. This obviously goes against the values of Decred.

The question arises: should we remove these types of services from the website? 

Alternatively, we could create a "custody" section where we explain the pros and cons and educate users about the risks of custodial solutions.

**Comment by jholdstock** [comment]
Personally I don't think we should list any custodial solutions at all.

Exchanges which take custody of coins, wallets where users don't control their own private keys, etc, should be removed from the site completely.

**Comment by alexlyp** [comment]
resolved.
