### ISSUE TITLE
Re-add flyp as instant exchange

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#721]
This instant exchange supports DCR: https://flyp.me/en/#/

Image: https://github.com/decred/dcrweb/blob/master/src/assets/images/exchanges/Flypme.jpg

Since the image is available in the assets map, I assume the service was removed at some point. I can confirm that their DCR exchange system works right now.

**Comment by jholdstock** [comment]
They were removed by #550 

I will re-add them now
