### ISSUE TITLE
Update "Buying And Trading Decred" section

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#76]
You can now use fiat currency to buy DCR from https://changelly.com/

If we wait for decred/dcrdocs#307 to be completed, we can add a link to the relevant section of dcrdocs (similar to how its currently done with exchanges)

**Comment by karamble** [comment]
can be closed as the tour guide on the landing page now pointing to the 'obtaining decred' docs page where all those exchanges are listed.

can be closed

**Comment by jolan** [comment]
Agreed, closing.
