### ISSUE TITLE
Mention/link mobile wallets and Matrix chat in the tour section of the landing page

### ISSUE THREAD

**Issue by zubairzia0** [decred/dcrweb#764]
The tour section on the landing page does not mention or have links to mobile wallets:
![image](https://user-images.githubusercontent.com/23157945/71966076-eef0bd80-31ce-11ea-9a3a-afd49f6f80ec.png)

We should mention of Matrix chat under the community section:

![image](https://user-images.githubusercontent.com/23157945/71969825-76d9c600-31d5-11ea-8803-1110b687d1e7.png)

**Comment by s-ben** [comment]
Is this issue still in play? Thinking of tweeting it out on the [Good First Issue (GFI) twitter accnt](https://twitter.com/dcrgoodfirst).

**Comment by jholdstock** [comment]
New website deployment is imminent (this week) so I wouldn't tweet right now. This issue may be closed after the new site is up

**Comment by alexlyp** [comment]
no longer relevant.
