### ISSUE TITLE
Update marketing contributors

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#771]
The following individuals should be removed:
* Elizabeth Bagot
* Leslie Ankney
* Margaret Huang
* Milvian Prieto
* Tim Hebel

**Comment by Dustorf** [comment]
Zubair should be moved from Strategy to Community
Bill Xing s/b removed from Community
Justin Santoro s/b removed from Design
Denis Zayets s/b removed from Community
Philip Conrod s/b removed from Community
I'd like to see Exitus added to Community, as well as Dominic
If they would be up for it, I think @degeri & @xaur s/b added to Community

**Comment by jzbz** [comment]
Dominic is already listed. All the other changes are fine. Not sure what we'll do for portraits of anons if they're game but I'm sure design will figure something out. No, neither of you can use Brad Pitt, I already asked for my self a few years ago.

**Comment by Dustorf** [comment]
I think illustrations of their avatars would do fine. 
Thanks for the correction on Dominic.

**Comment by xaur** [comment]
I'm not up for it but thanks for nomination.

**Comment by degeri** [comment]
I think I would fall more into development. But I fine being listed as long as its anon. But I really wanted brad pitt :P

**Comment by jholdstock** [comment]
The above PR implements all changes apart from adding Exitus (no portrait exists yet afaik)
