### ISSUE TITLE
Update contributors

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#775]
Add Exitus to Community - Portrait required
Remove rmykolas, Trace

**Comment by jholdstock** [comment]
Also remove rmykolas per the comment on #774

**Comment by jzbz** [comment]
Portrait is being worked on by @marcelolustosa.

Name: Mike Winslow
Matrix: @exitus:decred.org
Twitter: https://twitter.com/coveryfire7777
GitHub: https://github.com/exitus1

I'm thinking the marketing section would be most appropriate and we also need a title, maybe "Media Production" @exitus1 @Dustorf thoughts?

**Comment by exitus1** [comment]
Sounds good to me.

**Comment by marcelolustosa** [comment]
[Winslow.zip](https://github.com/decred/dcrweb/files/4167948/Winslow.zip)
![portraits](https://user-images.githubusercontent.com/39598223/73983099-64f25c80-4914-11ea-8d61-9ddb20573839.png)
