### ISSUE TITLE
Clarify that only active contributors are listed

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#781]
While making the list of past contributors (#744) and hall of fame (https://github.com/decredcommunity/issues/issues/52) is under discussion, easy but meaningful improvement is to clarify that the [Contributors](https://decred.org/contributors/) page only lists contractors who have been "recently" active. Ideally, also rougly explain how removals are handled (expectation management).

It would be nice to add a sentence or two thanking all contractors who are not currently active for their past contributions.

**Comment by xaur** [comment]
Triggered by [this chat](https://matrix.to/#/!psRvVbtljHXLzCBrjf:decred.org/$sHEoxxRXN0jLuCXhcHJXL6VyJATBWJXK2DIxy4IqgGI).

**Comment by alexlyp** [comment]
I don't think we need to clarify who is listed and why, nobody really cares, if someone feels a person should be added they can make a PR.
