### ISSUE TITLE
Update Business Brief section and fix outline section

### ISSUE THREAD

**Issue by 0xmzz** [decred/dcrweb#782]
The business brief section is an important page that can be used for a one-stop-shop kind of presentation, however it looks like it hasn't been updated since Q4 2018.

https://decred.org/brief/

also, the outline is a bit buggy and does not highlight what is clicked:

![image](https://user-images.githubusercontent.com/23157945/74070383-e60e2a00-49ce-11ea-974b-8452c96612c4.png)

**Comment by johncodesit** [comment]
@zubairzia0  Is there a requeriment specification for this page? I see how the outline is buggy, but do we have a design guideline on how to fix it? Thanks!
