### ISSUE TITLE
List of the Stakepools does not have a unique link

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#79]
The list of different stakepools on the Decred network is missing an own link (similar to /downloads/ or /brand/). This makes it hard to share this stakepool list with people. 

Currently the go-to-websites for the different stakepools are dcrstats.com (which favours its own stakepool) or docs.decred.org (which doesn't have live statistics).

Recommendation: add a unique link to make sharing easier.

**Comment by jzbz** [comment]
This would be handy. Telling people to scroll down to the bottom of the page and click "Stakepools" is less efficient than having an actual direct link to the info you can just paste...

**Comment by jolan** [comment]
There is https://decred.org/#modalOpen but that isn't a very good link. It should really be its own page.

**Comment by d7km** [comment]
Assigned: d7km
