### ISSUE TITLE
Social network links duplicated

### ISSUE THREAD

**Issue by kargakis** [decred/dcrweb#8]
I can access the Decred subreddit and Twitter page from two places in https://decred.org/  (top right and bottom right). Is this intentional?

**Comment by kargakis** [comment]
Same question applies for the Download button.

**Comment by kargakis** [comment]
Nevermind about the DL button, seems fine in those two places (or I haven't a better suggestion for it)

**Comment by jolan** [comment]
Yes it's intentional but could probably be replaced with different links that we want to highlight like the docs and stats sites.

**Comment by jolan** [comment]
I replaced those links with links to docs/stats since they're more useful.

Going to close this since the website will be undergoing a redesign as part of RFP 7 anyway:

https://forum.decred.org/threads/rfp-7-identity-alignment-and-design.3597/

**Comment by kargakis** [comment]
:+1:
