### ISSUE TITLE
add newsletter support

### ISSUE THREAD

**Issue by behindtext** [decred/dcrweb#804]
work has been done to add a newsletter subscription button to the new website, but it has been temporarily disabled in the interest of getting the new site deployed. the newsletter subscription button needs work done to make it work properly:

- [ ] create no-js modal that appears when the newsletter button is clicked that allows users to submit an email address, with a confirmation field where the user retypes their email address
- [ ] use a locally generated CAPTCHA or other mechanism to prevent scripting attacks. it would be ideal to have the solution not use js.
- [ ] connect to newsletter.decred.org (running phplist) and submit the new email address, to initiate the signup process
- [ ] test and verify that it is a simple matter of following a link in the footer of each newsletter email to unsubscribe

this list of requirements may change, and this is just a rough list of what needs to occur.

**Comment by johncodesit** [comment]
Hi @behindtext  this looks like a great feature, has anyone been working on it lately? If not, I could take it. Do we have any implementation similar to this? (for .CSS styling coherence).  BTW I'm new to decred, looking for my first good issue. ^^

**Comment by jholdstock** [comment]
Closing this off to tidy up the issues list. The newsletter effort is no longer being progressed. This issue can be reopened in future if we want to resume.
