### ISSUE TITLE
Add NOWPayments to payment processors

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#807]
Following up on https://github.com/decred/dcrweb/issues/458#issuecomment-581893846 now that the revamped site is up.

@NowPaymentsIO can you provide a SVG of your logo please?

**Comment by NowPaymentsIO** [comment]
@jzbz 
Hello, attaching .zip with our .svg logo inside.
[NOWPayments.svg.zip](https://github.com/decred/dcrweb/files/4292332/NOWPayments.svg.zip)
