### ISSUE TITLE
Add link to voting.decred.org to Adaptability section of homepage and on Adaptability page

### ISSUE THREAD

**Issue by RichardRed0x** [decred/dcrweb#813]
In the Adaptability section of the landing page, and on the Adaptability page, voting on changes to the consensus rules is alluded to but there is no link to the voting.decred.org page. This is a very useful page for following consensus change proposals, and as proposals.decred.org is linked to quite prominently I think this page should get similar treatment.

**Comment by Dustorf** [comment]
Yes, I think the link should be on: ""make changes to the consensus rules"
I don't see a link to proposals.decred.org, either. Could be done here: " Politeia Proposal System"

**Comment by dajohi** [comment]
or https://dcrdata.decred.org/agendas ?

**Comment by RichardRed0x** [comment]
I think the way it is presented on voting.decred.org is probably better for this.
