### ISSUE TITLE
News item rows – bottom edge padding

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#818]
The news item rows seem to have an significantly increased padding in the bottom edge. This applies to both the landing page and press/news subpage. 

The sizes of the rows should only increase in case the text won't fit on a single row, but keeping the padding the same (so only increasing per size of a row)

Specs: https://xd.adobe.com/view/014f1bdf-478a-42ad-59a2-23e78f33702b-777e/

<img width="1310" alt="Screenshot 2020-03-05 at 17 46 06" src="https://user-images.githubusercontent.com/17774057/75998257-36fb3a80-5f09-11ea-965c-11ed4496352e.png">

**Comment by Michae2xl** [comment]
Hey! what do you think about a Podcast Icone, for Decred in Depht as well?
