### ISSUE TITLE
Staking and Voting - navigation issues

### ISSUE THREAD

**Issue by linnutee** [decred/dcrweb#824]
Opening Staking and Voting from main navigation (Get Started/Staking and Voting) opens up https://decred.org/vsp/; 

However opening it from the breadcrumbs menu from any of the Get Started group subpages, opens up https://docs.decred.org/proof-of-stake/overview/ instead. 

These should both work the same way and open up the /vsp 

decred.org/vsp also is missing the breadcrumbs menu addition. 

Also considering the VSP page is bare bones and has not seen any love for a while, i'll remind about the open issue https://github.com/decred/dcrweb/issues/410. If anyone is up for creating simple and concentrated onboarding content, can work it into the page to give it some more meat. 

Use of https://docs.decred.org/proof-of-stake/overview/ in comparison is not something suitable for onboarding due to being as in depth and technical.

**Comment by karamble** [comment]
I like the idea of a route for onboarding on the VSP page, maybe @Dustorf could take a look at this.

**Comment by jholdstock** [comment]
The issues identified here are now resolved, and the new copy is provided in #837
