### ISSUE TITLE
Landing Page Header Distorted on 21:9 (Ultra-Wide) Aspect Ratio

### ISSUE THREAD

**Issue by exitus1** [decred/dcrweb#826]
![brokenheader](https://user-images.githubusercontent.com/46197055/76009600-757bff80-5edf-11ea-86ce-82443e5d828e.PNG)

Header image appears distorted on 21:9 aspect ratio - see Image.

**Comment by jholdstock** [comment]
Can you please retest now that #844 has been deployed?

**Comment by exitus1** [comment]
![image](https://user-images.githubusercontent.com/46197055/76632602-d62bbd80-6519-11ea-8a92-8e1ac39b90f8.PNG)
It looks like this now.

**Comment by jholdstock** [comment]
Any suggestions @linnutee? Perhaps anchor the background image to the left of the window?

**Comment by linnutee** [comment]
This can be closed imo. The background render is rather abstracted, so it's quite ok on larger viewports as it is right now. Only properties i'd look at is whether it's not loosing too much quality when scaled up.

The intent of these rendered forms is to create depth. The actual visibility of the DCR symbol there is meant to be subtle and just to create some relation to the forms. Given the nature how the bg image needs to scale, there is little difference in the big picture – whether the render is sometimes less visible as a whole or sometimes more.
