### ISSUE TITLE
Icon for podcasts

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#846]
@Michae2xl suggested in #818 that podcasts should have their own icon in the "Press" section. I'm moving the suggestion here because I am about to open a PR which closes #818.

Personally I think this is a neat idea.

**Comment by linnutee** [comment]
We do have one here already: https://github.com/decred/dcrweb/issues/561
https://xd.adobe.com/view/89fa7693-12b8-43a0-4841-32a12f827c8b-ffcb/

**Comment by Michae2xl** [comment]
Cool, so maybe we could change the name for (Decred in Depth, interviews)
