### ISSUE TITLE
New footer design

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#852]
The footer on all pages is currently the quick fix described in #819 and not the footer described in [the spec](https://xd.adobe.com/view/b7c058f2-e6e2-486f-65b9-2ca91a14a95a-c1f1/).

The full newly designed footer has not yet been implemented because we still do not have newsletter functionality, and it is not clear where the "Press Contacts" and "Licensing Information" links should point to.

**Comment by johncodesit** [comment]
@jholdstock  shouldn't this bug be closed? ^^

**Comment by jholdstock** [comment]
This issue was left open deliberately because, as written above, the footer is still not implemented as per the spec. #851 was just quick fix steps requested by @linnutee.

However, I do think its about time we close this issue. We still don't have newsletter functionality, press contacts, nor licensing information, and we probably never will. Given that the new footer seems to be heavily focused on these points, there doesn't seem to be much point implementing it.
