### ISSUE TITLE
Add OSL to list of OTC desks

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#858]
@3lian has mentioned that OSL now quotes DCR on their desk.

Link: https://osl.com/
Logo: https://osl.com/images/home/logo.svg

**Comment by 3lian** [comment]
Not yet quoted, one of their traders asked me today about having OSL as a OTC desk in our webpage, he asked me to wait till the end of the week as he is going to check for the desk to have DCR quoted. 

Keep you posted to have it on the exchanges page. 

Best!

**Comment by jholdstock** [comment]
Any updates for this one?

**Comment by 3lian** [comment]
Still waiting for their marketing team to confirm the quoting for cross mkt campaign, let you know as soon as I have an update. Cheers!
