### ISSUE TITLE
Add YouTube channel links

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#86]
At the bottom of the side menu where there are links to social media as well as on the site footer it would be good to have a link to the official YouTube channel.

https://www.youtube.com/channel/UCJ2bYDaPYHpSmJPh_M5dNSg

Also setting a custom URL for the YouTube channel is recommended so we can have something like https://www.youtube.com/channel/Decred as opposed to a random string of characters.

**Comment by pvtwarren** [comment]
If my pull request gets approved this should be fixed

**Comment by noahpierau** [comment]
#90 This issue is solved

**Comment by jolan** [comment]
Closed via #90.
