### ISSUE TITLE
Remove all "instant exchanges"

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#869]
This should remain open for a while so we can discuss having a policy were we remove the existing instant exchanges and no longer add new ones to our exchanges page.

There seems to be new ones that pop up regularly, it's annoying for community members to have to test them out and there's no guarantee that they will continue to work. With the advent of instant exchange aggregators it now seems like it's just a game to show a super low rate and collect affiliate kickbacks.

**Comment by xaur** [comment]
I like the idea to raise the bar for the /exchanges page. We can collect the knowledge about community testing of various services elsewhere and I can help structuring it.

**Comment by noahpierau** [comment]
There must be a middle way, I think the legit instant exchanges should be displayed on our main website. Instant exchanges are a fast way to go from crypto to crypto without KYC. Perhaps we could require new, untested exchanges to be live for at least X months before we add them?
