### ISSUE TITLE
Add BitChute to Community page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#889]
Mirroring content on BitChute was announced in the [May 3, 2020](https://www.youtube.com/watch?v=oHqzvN3TMU0) bi-weekly update. Let's add the BitChute link to the /community page so that it is both more visible and also a way to know the correct link to prevent impostors.

https://www.bitchute.com/channel/decred/

@exitus 1 please confirm above is the correct link.

**Comment by jzbz** [comment]
This can be closed, we're not on there anymore.
