### ISSUE TITLE
support landing page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#890]
It would be good to have a short and easy to remember `decred.org/support` link with direct links to support chat rooms:

- https://chat.decred.org/#/room/!dhHYPTtCtvPSUfTepT:decred.org
- https://discord.com/channels/349993843728449537/350007452152102923
- https://t.me/DecredSupport

**Comment by jholdstock** [comment]
Such a page could also link to various FAQs and troubleshooting on docs.decred.org, and mention that bugs should ideally be reported as GitHub issues.

**Comment by xaur** [comment]
There is no https://decred.org/support but I see support links at https://decred.org/community/ . The latter also includes the "Admins will never DM you..." warning suggested in #1027. So #1056 is definitely an improvement for getting a support entry point.

Things we can still consider from this issue are:

- Direct link to `#support` chat https://chat.decred.org/#/room/#support:decred.org
  - Finding a chat room is a common question from new Element users
- Direct link to [Joining Matrix](https://docs.decred.org/getting-started/joining-matrix-channels/) since it is not so trivial compared to more established Discord and Telegram
  - This also helps the non-support use case of the Community page
- "link to various FAQs and troubleshooting on docs.decred.org"
  - We can use [FAQ/General](https://docs.decred.org/faq/general/) or something else? 
- "mention that bugs should ideally be reported as GitHub issues"
