### ISSUE TITLE
https://decred.org/matrix/ font too small on large screen

### ISSUE THREAD

**Issue by alexlyp** [decred/dcrweb#899]
User is reporting that the font is too hard to read on a very high resolution display.  Possibly some way to scale font based on resolution?  Not sure it's possible.

**Comment by jholdstock** [comment]
Fonts on the `/matrix` page seem to be the same as every other page so if anything is updated here, it should probably be updated everywhere.

**Comment by linnutee** [comment]
Yep it's the same, assuming the viewer might have zoomed out on browser? 

Regarding the page, is there any practical need of having it at all? The current version is a fairly crude one based off a prior slack signup page with a whole lot of unnecessary text and imagery, so I would argue it probably doesn't help with the sign-up process.

Being a tutorial, the page should differ from the rest of the dcrweb layouts and purely focus on highlighting each of the steps, drop all other bloat.

**Comment by jholdstock** [comment]
The page was created before the docs page exists. We could possibly remove https://decred.org/matrix and redirect that URL to 
https://docs.decred.org/getting-started/joining-matrix-channels/

**Comment by jholdstock** [comment]
Closing this issue based on comments above. Will investigate consolidating Matrix signup instructions into a single URL at chat.decred.org
