### ISSUE TITLE
Add LatAm marketing team to contributors page

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#908]
Lustosa has completed a set of portraits so we're ready to add a new batch of contractors to the site.

[AR_portraits.zip](https://github.com/decred/dcrweb/files/5190750/AR_portraits.zip)

---

**Camilo ?**
Title: Outreach Argentina
**<Matrix?>**
https://github.com/camilolwi

---

Carolina Ibarra
**Title: <?>**
@caibarrad:decred.org
https://twitter.com/caibarrad
https://www.linkedin.com/in/caibarrad

---

Victor Rubin
@victorarubin:matrix.org
**Title: <?>**
https://twitter.com/victorarubin

---

Lorena Franco
**Title: <?>**
@francov_:decred.org
https://twitter.com/Francov99_
https://github.com/francov99

---

Pablito Labarta
Title: Content Production
@pablito:decred.org
https://twitter.com/plabarta_
https://github.com/plabarta
https://medium.com/@pablit0

---

Ana Chávez
Title: Alternative Outreach
@adcade:matrix.org
https://twitter.com/addcade

---

Ignacio Rodriguez
Title: Designer
@nachito:decred.org
https://github.com/Reidiojed

---

Tomas Grooss
Title: Operations Argentina
@tomee:decred.org
https://twitter.com/tomasgroos
https://github.com/TomeeGrooss

**Comment by pLabarta** [comment]
Title: Content Production
The rest looks good :D

**Comment by Reidiojed** [comment]
Ignacio Rodriguez
Title: Designer

thanks!

**Comment by jholdstock** [comment]
@jzbz - I've updated your comment to include the extra info provided by @pLabarta and @Reidiojed, and also filled in a couple of gaps myself.

**Comment by 3lian** [comment]
hi @jzbz @jholdstock, adding details in bold: 

Camilo **Rodriguez**
Title: Outreach Argentina
<Matrix?>
https://github.com/camilolwi

---

Carolina Ibarra
Title: **Operations Colombia**
@caibarrad:decred.org
https://twitter.com/caibarrad
https://www.linkedin.com/in/caibarrad

---

Victor Rubin
@victorarubin:matrix.org
Title: **Content Production** 
https://twitter.com/victorarubin

---

Lorena Franco
Title: **Social Media Manager**
@francov_:decred.org
https://twitter.com/Francov99_
https://github.com/francov99

---

Ana Chávez
Title: **BizDev and Outreach**
@adcade:matrix.org
https://twitter.com/addcade

--- 

About my titile, wanted to ask you if you could change it to "**Latam Ops**" please. 

--- 

Thanks!!
