### ISSUE TITLE
Add localization selection/detection.

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#92]
`dcrweb` is currently being translated into over a dozen languages by the `#international_ops` team (four are complete so far).

It would be nice to put the necessary pieces into place so we can offer users of the site the option to choose their native language and possibly even auto-detect the default browser language and show them the appropriate translation.

**Comment by peterzen** [comment]
I've rebased the PR onto master – It should be good for deployment on a *.decred.org staging site for bug hunting (and for sorting out the server side setup) while the rest of the translations are being worked on:

https://github.com/decred/dcrweb/pull/88

**Comment by dajohi** [comment]
#88 merged
