### ISSUE TITLE
Add vspd operators to /vsp

### ISSUE THREAD

**Issue by dajohi** [decred/dcrweb#920]
https://www.decred.org/vsp should show vspd (v3) servers and stats.

**Comment by jholdstock** [comment]
I don't think we should work on this until we have decrediton 1.6 out, with a thoroughly tested and proven interface for using vspd. 

Also delaying updating docs.decred.org with vspd, for the same reason.

**Comment by xaur** [comment]
A quick way to implement this is to add a new table for vspds, and add a title like "Legacy VSP servers (dcrstakepool)" on the existing table.

It would be good to add short text summarizing the differences and linking to proper docs page.
