### ISSUE TITLE
Add NovaDAX to the list of fiat exchages - Brazil

### ISSUE THREAD

**Issue by Michae2xl** [decred/dcrweb#921]
![NovaDAX-logos-13](https://user-images.githubusercontent.com/44928059/96944669-716e1380-14a9-11eb-9cd7-7daf48706bb9.png)
![novadax](https://user-images.githubusercontent.com/44928059/96944671-729f4080-14a9-11eb-9b3b-c863d19ce705.png)

**Comment by jholdstock** [comment]
Hi @Michae2xl 

Just had a look on https://www.novadax.com.br/ and I cant find Decred listed here?

**Comment by Michae2xl** [comment]
Hey 
![image](https://user-images.githubusercontent.com/44928059/97047300-be53f780-1546-11eb-8299-34bd57583b2a.jpeg)

**Comment by Michae2xl** [comment]
https://www.novadax.com.br/product/orderbook?pair=DCR_BRL
