### ISSUE TITLE
Showcase v1.6 features straight on the home page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#923]
> With the upcoming 1.6 release imminent for public release and major features just over the horizon. I think it behooves us to think about renovating the decred homepage to reflect this new era in DCR. Assuming there isn’t already a plan in place to change up the landing page. 1.6 will bring new and old eyes to the website and we should take advantage of that renewed interest because if we don’t, that’s a major missed opportunity in my humble opinion. If there’s already a plan, make it badass. ([u/Atom_Blue](https://www.reddit.com/r/decred/comments/jgzs57/forward_thinking_friday_23_october_2020_the/g9v16h2/) on Reddit)

Sounds like a great idea to me. Imagine if it was possible to grasp the new game-changing features of v1.6 straight from the home page in just a few seconds. With sweet screencuts.

**Comment by xaur** [comment]
Perhaps not only v1.6 features but all killer features. For example, I client filter SPV is one of the underrated ones. I can't overstate how huge it is to remove an entire layer of middleware from the equation.

https://bchd.cash/ has a nice section on it:

> Neutrino's client-side filtering is the future of SPV wallets

**Comment by xaur** [comment]
Uh wait they went much further and built a whole website dedicated to their cfilter-based SPV wallet: https://neutrino.cash/

I won't comment on the styling but big wallet shots with BIG letters explaining how it is great is well deserved for the tech.

**Comment by xaur** [comment]
I posted this for the planetdecred.org website in https://github.com/planetdecred/website/issues/25 but the same applies to decred.org. Decred software products are under-presented on our websites, compared to projects who (arguably) have a better "business grip".

I think we could have a landing page for each core product like dcrd, dcrwallet, decrediton, dcrdata, etc. For example, [bchd.cash](https://bchd.cash/) is literally selling (in a good way) their chain daemon product for the technical audience (anyone who would run a full node), but it might intrigue/impress even casual visitors.

**Comment by jholdstock** [comment]
Thanks for sharing these @xaur. I am working on something for this and will share with you once I have something ready.

**Comment by jholdstock** [comment]
https://decred.org/release

**Comment by xaur** [comment]
Nice, I think we can close this unless you have more ideas for this issue.
