### ISSUE TITLE
Add DCRDEX to exchanges page

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#924]
URL: https://dex.decred.org/
Logo: https://dex.decred.org/images/landing-logo.svg

Don't forget to tag it for the "atomic swaps" filter and "high liquidity".

**Comment by HlloWrld** [comment]
I will try and work on this

**Comment by HlloWrld** [comment]
I've got everything done except for adding the tag for 'High Liquidity' and ' Atomic Swaps'. I was also going to add the 'Decentralized' tag as well. I've added the tags correctly AFAIK. I will keep at it

**Comment by jholdstock** [comment]
@HlloWrld  thanks again for your contribution, but please note that I am having to close this issue manually because you did not follow the steps in the doc I linked. Please remember to add "Closes #924" or "Resolves #924" to the PR description or commit message next time :)
