### ISSUE TITLE
Wrong filename of dcrdex press release

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#925]
https://github.com/decred/dcrweb/blob/master/src/content/press/2018-10-21_dex_launch.md

should have 2020 in it.

The press release is also missing from the [press](https://decred.org/press/) page, not sure if it's related to this bug.

**Comment by jholdstock** [comment]
Good catch on the filename.

To see it on the press page you need to switch the Coverage/Releases filter on the right.
