### ISSUE TITLE
Press releases cannot be accessed with javascript off

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#929]
At https://decred.org/press/ , the switch between Coverage and Releases works without js (I guess it's some CSS black magic). On the Coverage tab I can click and follow external links. But on the Releases tab clicking them does nothing.

Besides not being accessible without js, another downside is press release X cannot be linked directly. This may have implications on search results.

Another (small) side effect is such implementation carries all content in hidden HTML blocks and will keep growing with every new item.

For all these reasons I suggest to convert Press Releases to normal pages.

**Comment by jholdstock** [comment]
Good suggestion :+1:  Each press release on its own page makes a lot of sense
