### ISSUE TITLE
Download links for China

### ISSUE THREAD

**Issue by jzbz** [decred/dcrweb#95]
GitHub uses AWS for serving files, so it is not possible to download anything linked on decred.org from inside China without the use of a VPN. Our Chinese users have resorted to re-hosting the binaries to get around this, however it is not ideal from a security standpoint as I'm sure few are verifying them with PGP.

If we could detect users from China and provide them with alternate download sources that would be ideal.

**Comment by jcvernaleo** [comment]
Is github completely blocked in china or is it just the file hosting?  Just want to know if they could use PGP to verify in principle (even though I know most would not).

**Comment by jzbz** [comment]
GitHub is not blocked (it has been blocked on a few occasions temporarily
though) the issue is AWS is blocked so everything that is hosted there is
off limits.

**Comment by jcvernaleo** [comment]
Where would you suggest hosting such files?  We actually end up with a lot of files up on github.  So far,, all of the github releases based on my local copies:
```
jcv@triforce decred-releases $ du -sh
16G	.
```

**Comment by jzbz** [comment]
Here are 3 options that should work:

https://www.alibabacloud.com/
https://www.ucloud.cn/
https://www.upyun.com/

Alibaba seems like the right choice since they offer an English interface and are the largest.

**Comment by detailyang** [comment]
@jzbz  @jcvernaleo
Yep, AWS is blocked at china. Your 3 options is okay to serve chinese guys. But if you just want to provide the file, i think i can help you with CDN

**Comment by detailyang** [comment]
Or you can consider to use [alibaba CDN product](https://www.alibabacloud.com/product/cdn) for serving binary file which price is not too much.

**Comment by jpz** [comment]
Downloads are fairly slow in Australia also - while not super problematic (it takes about 90secs to download 70MB decrediton.dmg), a CDN would improve that by putting the data on the edge nodes - so there's some _other_ utility in implementing a CDN for the downloads.

Is AWS Cloudfront also blocked?  If it's just the github s3 buckets which are blocked, that could fix the situation.

**Comment by detailyang** [comment]
S3 bucks is blocked. But it looks like Cloudfront is okay now, you can easily test it by [greatfirewallofchina](http://www.greatfirewallofchina.org/index.php?siteurl=http%3A%2F%2Fdq4ijymydgrfx.cloudfront.net%2F)

If some country is slow too,  AWS Cloudfront  it a good choice:)

**Comment by jzbz** [comment]
@detailyang Can you confirm weather or not our download links are working from inside China right now?
Thanks.

**Comment by detailyang** [comment]
@jzbz It's okay now. BTW, Chinese users almost know how to use VPN else they cannot access most crypto exchanges:)
