### ISSUE TITLE
Contributor page maintenance

### ISSUE THREAD

**Issue by jholdstock** [decred/dcrweb#955]
Some suggestions from Matrix:

Category changes to consider:
- remove strategy
- merge community with marketing
- create research for people like richardred, bee, etc

Add developers (pic required):
- buck
- wisdom

### The following was done in #990

~Candidates for removal:~
- ~jessica eggleston~
- ~scott christian~
- ~zubair~
- ~dmitry fedorov~
- ~seth benton~

~Review dev titles:~
- ~raedah "Project Lead/Manager~

~Move Nick K to design~

**Comment by dreacot** [comment]
Is this still being followed up on? Seems like there would need to be a central discussion from community members on what the updated info should be, so nothing is lost.

Let me know what you think, I could pick this up

**Comment by jholdstock** [comment]
Contributor page has been removed
