### ISSUE TITLE
Mention full release notes at the release page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#962]
At the end of the [release](https://decred.org/release/) landing page it says

> Click here to download Decred 1.6 **command line tools**  ↓

and links to https://github.com/decred/decred-binaries/releases/tag/v1.6.1

but that link has so much more: links to all GUI and CLI variants for all architectures, hashes, signatures, and full release notes detailing what exactly has changed. I think calling it all "command line tools" is misleading to all non-CLI users who could find something useful at the GitHub release page.

I suggest to rename this link to something like

> Click here to read full release notes and a full list of downloads

**Comment by jholdstock** [comment]
Page no longer exists, closing
