### ISSUE TITLE
Mention download verification on the release page

### ISSUE THREAD

**Issue by xaur** [decred/dcrweb#964]
[Release](https://decred.org/release/) page is not routing users through download verification like GitHub [release](https://github.com/decred/decred-binaries/releases/tag/v1.6.1) does.

I know it is a "sensitive" topic because we want a good balance between not standing in the way of newcomers and promoting good security practices.

Still, I would dedicate one line of text immediately under the [download](https://decred.org/release/#downloads) buttons, saying something like

> [Click here to verify the downloads]

or

> [Click here to verify that the downloads have not been tampered with]

**Comment by xaur** [comment]
[dex.decred.org](https://dex.decred.org/) implemented it in https://github.com/decred/dexweb/pull/14 as follows:

![dex-verify](https://user-images.githubusercontent.com/24484727/118087638-616e4080-b3b5-11eb-8028-2a0d5687fc46.png)

**Comment by xaur** [comment]
For some inspiration, Ledger is doing it on their downloads [page](https://www.ledger.com/ledger-live/download) _before_ the download buttons. I wouldn't use their wording "the only page to download X" since the source doesn't really matter if sigs match. But it is worth considering to put the notice before the downloads.

**Comment by jholdstock** [comment]
Page no longer exists, closing this issue
