### ISSUE TITLE
Change the Bitvavo Logo and Link

### ISSUE THREAD

**Issue by noahpierau** [decred/dcrweb#999]
This issue was created on behalf of Bitvavo, one of the biggest regulated EUR exchanges in Europe. Bitvavo is proudly based in Amsterdam and has been offering the DCR/EUR trading pair for some time now. 

On your website we saw the page https://decred.org/exchanges/ where you showcase some available exchange options for DCR. Bitvavo is proud to be on that list!

Currently we are in the process of launching a new website with a redesigned logo. We hope you will support us by **changing the Bitvavo logo on your website**. Kindly send us the required logo dimensions and file format (png, jpg, svg) for your website, our designers will be able to create it for you.

Apart from that, we are preparing an updated asset page for you to link to: https://bitvavo.com/en/decred (for localized versions of the website just replace "en" with "de", "es", "fr", "it" or "nl", also reachable via the footer). If you see any inaccurate information in there, please do let us know as well. 

Best regards,

https://bitvavo.com/en
Bitvavo B.V.
Herengracht 450
1017 CA Amsterdam
The Netherlands

**Comment by jholdstock** [comment]
Hey Noah, hope you're well. A .png at 608x280px would be ideal.

**Comment by noahpierau** [comment]
Hey @jholdstock 

Yes, all is well with me! Attached you can find the Bitvavo logo in the required size and file format:

![bitvavo-dcr](https://user-images.githubusercontent.com/16287891/135423664-e245ce63-fba9-4ca5-8cf2-6c91ae2f3265.png)

Thank you for taking the time to work on this. We recommend a link to the custom DCR page: https://bitvavo.com/en/decred (for localized versions, just replace "en" with "de", "es", "fr", "it" or "nl" in the link). Linking to https://bitvavo.com is possible as well.

Kindly let us know if you need any additional information.
